/*
 * This file is generated by jOOQ.
 */
package eki.ekilex.data.db.main.tables.records;


import eki.ekilex.data.db.main.tables.ConstructMemberPosGroup;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConstructMemberPosGroupRecord extends UpdatableRecordImpl<ConstructMemberPosGroupRecord> implements Record4<Long, Long, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.construct_member_pos_group.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.construct_member_pos_group.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.construct_member_pos_group.construct_member_id</code>.
     */
    public void setConstructMemberId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.construct_member_pos_group.construct_member_id</code>.
     */
    public Long getConstructMemberId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.construct_member_pos_group.pos_group_code</code>.
     */
    public void setPosGroupCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.construct_member_pos_group.pos_group_code</code>.
     */
    public String getPosGroupCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.construct_member_pos_group.order_by</code>.
     */
    public void setOrderBy(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.construct_member_pos_group.order_by</code>.
     */
    public Long getOrderBy() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, String, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Long, String, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ConstructMemberPosGroup.CONSTRUCT_MEMBER_POS_GROUP.ID;
    }

    @Override
    public Field<Long> field2() {
        return ConstructMemberPosGroup.CONSTRUCT_MEMBER_POS_GROUP.CONSTRUCT_MEMBER_ID;
    }

    @Override
    public Field<String> field3() {
        return ConstructMemberPosGroup.CONSTRUCT_MEMBER_POS_GROUP.POS_GROUP_CODE;
    }

    @Override
    public Field<Long> field4() {
        return ConstructMemberPosGroup.CONSTRUCT_MEMBER_POS_GROUP.ORDER_BY;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getConstructMemberId();
    }

    @Override
    public String component3() {
        return getPosGroupCode();
    }

    @Override
    public Long component4() {
        return getOrderBy();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getConstructMemberId();
    }

    @Override
    public String value3() {
        return getPosGroupCode();
    }

    @Override
    public Long value4() {
        return getOrderBy();
    }

    @Override
    public ConstructMemberPosGroupRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ConstructMemberPosGroupRecord value2(Long value) {
        setConstructMemberId(value);
        return this;
    }

    @Override
    public ConstructMemberPosGroupRecord value3(String value) {
        setPosGroupCode(value);
        return this;
    }

    @Override
    public ConstructMemberPosGroupRecord value4(Long value) {
        setOrderBy(value);
        return this;
    }

    @Override
    public ConstructMemberPosGroupRecord values(Long value1, Long value2, String value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConstructMemberPosGroupRecord
     */
    public ConstructMemberPosGroupRecord() {
        super(ConstructMemberPosGroup.CONSTRUCT_MEMBER_POS_GROUP);
    }

    /**
     * Create a detached, initialised ConstructMemberPosGroupRecord
     */
    public ConstructMemberPosGroupRecord(Long id, Long constructMemberId, String posGroupCode, Long orderBy) {
        super(ConstructMemberPosGroup.CONSTRUCT_MEMBER_POS_GROUP);

        setId(id);
        setConstructMemberId(constructMemberId);
        setPosGroupCode(posGroupCode);
        setOrderBy(orderBy);
    }
}
