/*
 * This file is generated by jOOQ.
 */
package eki.ekilex.data.db.main.tables.records;


import eki.ekilex.data.db.main.tables.ViewWwLexemeRelation;

import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewWwLexemeRelationRecord extends TableRecordImpl<ViewWwLexemeRelationRecord> implements Record2<Long, JSON> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.view_ww_lexeme_relation.lexeme_id</code>.
     */
    public void setLexemeId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.view_ww_lexeme_relation.lexeme_id</code>.
     */
    public Long getLexemeId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.view_ww_lexeme_relation.related_lexemes</code>.
     */
    public void setRelatedLexemes(JSON value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.view_ww_lexeme_relation.related_lexemes</code>.
     */
    public JSON getRelatedLexemes() {
        return (JSON) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, JSON> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, JSON> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ViewWwLexemeRelation.VIEW_WW_LEXEME_RELATION.LEXEME_ID;
    }

    @Override
    public Field<JSON> field2() {
        return ViewWwLexemeRelation.VIEW_WW_LEXEME_RELATION.RELATED_LEXEMES;
    }

    @Override
    public Long component1() {
        return getLexemeId();
    }

    @Override
    public JSON component2() {
        return getRelatedLexemes();
    }

    @Override
    public Long value1() {
        return getLexemeId();
    }

    @Override
    public JSON value2() {
        return getRelatedLexemes();
    }

    @Override
    public ViewWwLexemeRelationRecord value1(Long value) {
        setLexemeId(value);
        return this;
    }

    @Override
    public ViewWwLexemeRelationRecord value2(JSON value) {
        setRelatedLexemes(value);
        return this;
    }

    @Override
    public ViewWwLexemeRelationRecord values(Long value1, JSON value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewWwLexemeRelationRecord
     */
    public ViewWwLexemeRelationRecord() {
        super(ViewWwLexemeRelation.VIEW_WW_LEXEME_RELATION);
    }

    /**
     * Create a detached, initialised ViewWwLexemeRelationRecord
     */
    public ViewWwLexemeRelationRecord(Long lexemeId, JSON relatedLexemes) {
        super(ViewWwLexemeRelation.VIEW_WW_LEXEME_RELATION);

        setLexemeId(lexemeId);
        setRelatedLexemes(relatedLexemes);
    }
}
