/*
 * This file is generated by jOOQ.
 */
package eki.ekilex.data.db.main.tables.records;


import eki.ekilex.data.db.main.tables.WordEtymGroupTree;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WordEtymGroupTreeRecord extends UpdatableRecordImpl<WordEtymGroupTreeRecord> implements Record4<Long, Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.word_etym_group_tree.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.word_etym_group_tree.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.word_etym_group_tree.parent_word_etym_group_id</code>.
     */
    public void setParentWordEtymGroupId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.word_etym_group_tree.parent_word_etym_group_id</code>.
     */
    public Long getParentWordEtymGroupId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.word_etym_group_tree.child_word_etym_group_id</code>.
     */
    public void setChildWordEtymGroupId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.word_etym_group_tree.child_word_etym_group_id</code>.
     */
    public Long getChildWordEtymGroupId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.word_etym_group_tree.order_by</code>.
     */
    public void setOrderBy(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.word_etym_group_tree.order_by</code>.
     */
    public Long getOrderBy() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, Long, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Long, Long, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return WordEtymGroupTree.WORD_ETYM_GROUP_TREE.ID;
    }

    @Override
    public Field<Long> field2() {
        return WordEtymGroupTree.WORD_ETYM_GROUP_TREE.PARENT_WORD_ETYM_GROUP_ID;
    }

    @Override
    public Field<Long> field3() {
        return WordEtymGroupTree.WORD_ETYM_GROUP_TREE.CHILD_WORD_ETYM_GROUP_ID;
    }

    @Override
    public Field<Long> field4() {
        return WordEtymGroupTree.WORD_ETYM_GROUP_TREE.ORDER_BY;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getParentWordEtymGroupId();
    }

    @Override
    public Long component3() {
        return getChildWordEtymGroupId();
    }

    @Override
    public Long component4() {
        return getOrderBy();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getParentWordEtymGroupId();
    }

    @Override
    public Long value3() {
        return getChildWordEtymGroupId();
    }

    @Override
    public Long value4() {
        return getOrderBy();
    }

    @Override
    public WordEtymGroupTreeRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public WordEtymGroupTreeRecord value2(Long value) {
        setParentWordEtymGroupId(value);
        return this;
    }

    @Override
    public WordEtymGroupTreeRecord value3(Long value) {
        setChildWordEtymGroupId(value);
        return this;
    }

    @Override
    public WordEtymGroupTreeRecord value4(Long value) {
        setOrderBy(value);
        return this;
    }

    @Override
    public WordEtymGroupTreeRecord values(Long value1, Long value2, Long value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WordEtymGroupTreeRecord
     */
    public WordEtymGroupTreeRecord() {
        super(WordEtymGroupTree.WORD_ETYM_GROUP_TREE);
    }

    /**
     * Create a detached, initialised WordEtymGroupTreeRecord
     */
    public WordEtymGroupTreeRecord(Long id, Long parentWordEtymGroupId, Long childWordEtymGroupId, Long orderBy) {
        super(WordEtymGroupTree.WORD_ETYM_GROUP_TREE);

        setId(id);
        setParentWordEtymGroupId(parentWordEtymGroupId);
        setChildWordEtymGroupId(childWordEtymGroupId);
        setOrderBy(orderBy);
    }
}
