/*
 * This file is generated by jOOQ.
 */
package eki.wordweb.data.db.tables.records;


import eki.wordweb.data.db.tables.MviewOdWordRelationIdx;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MviewOdWordRelationIdxRecord extends TableRecordImpl<MviewOdWordRelationIdxRecord> implements Record6<Long, Long, String, Long, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mview_od_word_relation_idx.word_id</code>.
     */
    public void setWordId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mview_od_word_relation_idx.word_id</code>.
     */
    public Long getWordId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.mview_od_word_relation_idx.word_relation_id</code>.
     */
    public void setWordRelationId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mview_od_word_relation_idx.word_relation_id</code>.
     */
    public Long getWordRelationId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.mview_od_word_relation_idx.word_rel_type_code</code>.
     */
    public void setWordRelTypeCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mview_od_word_relation_idx.word_rel_type_code</code>.
     */
    public String getWordRelTypeCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mview_od_word_relation_idx.related_word_id</code>.
     */
    public void setRelatedWordId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mview_od_word_relation_idx.related_word_id</code>.
     */
    public Long getRelatedWordId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.mview_od_word_relation_idx.value</code>.
     */
    public void setValue(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mview_od_word_relation_idx.value</code>.
     */
    public String getValue() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.mview_od_word_relation_idx.value_as_word</code>.
     */
    public void setValueAsWord(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mview_od_word_relation_idx.value_as_word</code>.
     */
    public String getValueAsWord() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, String, Long, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, String, Long, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MviewOdWordRelationIdx.MVIEW_OD_WORD_RELATION_IDX.WORD_ID;
    }

    @Override
    public Field<Long> field2() {
        return MviewOdWordRelationIdx.MVIEW_OD_WORD_RELATION_IDX.WORD_RELATION_ID;
    }

    @Override
    public Field<String> field3() {
        return MviewOdWordRelationIdx.MVIEW_OD_WORD_RELATION_IDX.WORD_REL_TYPE_CODE;
    }

    @Override
    public Field<Long> field4() {
        return MviewOdWordRelationIdx.MVIEW_OD_WORD_RELATION_IDX.RELATED_WORD_ID;
    }

    @Override
    public Field<String> field5() {
        return MviewOdWordRelationIdx.MVIEW_OD_WORD_RELATION_IDX.VALUE;
    }

    @Override
    public Field<String> field6() {
        return MviewOdWordRelationIdx.MVIEW_OD_WORD_RELATION_IDX.VALUE_AS_WORD;
    }

    @Override
    public Long component1() {
        return getWordId();
    }

    @Override
    public Long component2() {
        return getWordRelationId();
    }

    @Override
    public String component3() {
        return getWordRelTypeCode();
    }

    @Override
    public Long component4() {
        return getRelatedWordId();
    }

    @Override
    public String component5() {
        return getValue();
    }

    @Override
    public String component6() {
        return getValueAsWord();
    }

    @Override
    public Long value1() {
        return getWordId();
    }

    @Override
    public Long value2() {
        return getWordRelationId();
    }

    @Override
    public String value3() {
        return getWordRelTypeCode();
    }

    @Override
    public Long value4() {
        return getRelatedWordId();
    }

    @Override
    public String value5() {
        return getValue();
    }

    @Override
    public String value6() {
        return getValueAsWord();
    }

    @Override
    public MviewOdWordRelationIdxRecord value1(Long value) {
        setWordId(value);
        return this;
    }

    @Override
    public MviewOdWordRelationIdxRecord value2(Long value) {
        setWordRelationId(value);
        return this;
    }

    @Override
    public MviewOdWordRelationIdxRecord value3(String value) {
        setWordRelTypeCode(value);
        return this;
    }

    @Override
    public MviewOdWordRelationIdxRecord value4(Long value) {
        setRelatedWordId(value);
        return this;
    }

    @Override
    public MviewOdWordRelationIdxRecord value5(String value) {
        setValue(value);
        return this;
    }

    @Override
    public MviewOdWordRelationIdxRecord value6(String value) {
        setValueAsWord(value);
        return this;
    }

    @Override
    public MviewOdWordRelationIdxRecord values(Long value1, Long value2, String value3, Long value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MviewOdWordRelationIdxRecord
     */
    public MviewOdWordRelationIdxRecord() {
        super(MviewOdWordRelationIdx.MVIEW_OD_WORD_RELATION_IDX);
    }

    /**
     * Create a detached, initialised MviewOdWordRelationIdxRecord
     */
    public MviewOdWordRelationIdxRecord(Long wordId, Long wordRelationId, String wordRelTypeCode, Long relatedWordId, String value, String valueAsWord) {
        super(MviewOdWordRelationIdx.MVIEW_OD_WORD_RELATION_IDX);

        setWordId(wordId);
        setWordRelationId(wordRelationId);
        setWordRelTypeCode(wordRelTypeCode);
        setRelatedWordId(relatedWordId);
        setValue(value);
        setValueAsWord(valueAsWord);
    }
}
