/*
 * This file is generated by jOOQ.
 */
package eki.ekilex.data.db.tables;


import eki.ekilex.data.db.Indexes;
import eki.ekilex.data.db.Keys;
import eki.ekilex.data.db.Public;
import eki.ekilex.data.db.tables.records.AspectRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Aspect extends TableImpl<AspectRecord> {

    private static final long serialVersionUID = 1874259430;

    /**
     * The reference instance of <code>public.aspect</code>
     */
    public static final Aspect ASPECT = new Aspect();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AspectRecord> getRecordType() {
        return AspectRecord.class;
    }

    /**
     * The column <code>public.aspect.code</code>.
     */
    public final TableField<AspectRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.aspect.datasets</code>.
     */
    public final TableField<AspectRecord, String[]> DATASETS = createField("datasets", org.jooq.impl.SQLDataType.VARCHAR(10).getArrayDataType(), this, "");

    /**
     * The column <code>public.aspect.order_by</code>.
     */
    public final TableField<AspectRecord, Long> ORDER_BY = createField("order_by", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('aspect_order_by_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * Create a <code>public.aspect</code> table reference
     */
    public Aspect() {
        this(DSL.name("aspect"), null);
    }

    /**
     * Create an aliased <code>public.aspect</code> table reference
     */
    public Aspect(String alias) {
        this(DSL.name(alias), ASPECT);
    }

    /**
     * Create an aliased <code>public.aspect</code> table reference
     */
    public Aspect(Name alias) {
        this(alias, ASPECT);
    }

    private Aspect(Name alias, Table<AspectRecord> aliased) {
        this(alias, aliased, null);
    }

    private Aspect(Name alias, Table<AspectRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Aspect(Table<O> child, ForeignKey<O, AspectRecord> key) {
        super(child, key, ASPECT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ASPECT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AspectRecord, Long> getIdentity() {
        return Keys.IDENTITY_ASPECT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AspectRecord> getPrimaryKey() {
        return Keys.ASPECT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AspectRecord>> getKeys() {
        return Arrays.<UniqueKey<AspectRecord>>asList(Keys.ASPECT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Aspect as(String alias) {
        return new Aspect(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Aspect as(Name alias) {
        return new Aspect(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Aspect rename(String name) {
        return new Aspect(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Aspect rename(Name name) {
        return new Aspect(name, null);
    }
}
