/*
 * This file is generated by jOOQ.
 */
package eki.ekilex.data.db.tables;


import eki.ekilex.data.db.Indexes;
import eki.ekilex.data.db.Keys;
import eki.ekilex.data.db.Public;
import eki.ekilex.data.db.tables.records.FreeformSourceLinkRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FreeformSourceLink extends TableImpl<FreeformSourceLinkRecord> {

    private static final long serialVersionUID = -791353442;

    /**
     * The reference instance of <code>public.freeform_source_link</code>
     */
    public static final FreeformSourceLink FREEFORM_SOURCE_LINK = new FreeformSourceLink();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FreeformSourceLinkRecord> getRecordType() {
        return FreeformSourceLinkRecord.class;
    }

    /**
     * The column <code>public.freeform_source_link.id</code>.
     */
    public final TableField<FreeformSourceLinkRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('freeform_source_link_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.freeform_source_link.freeform_id</code>.
     */
    public final TableField<FreeformSourceLinkRecord, Long> FREEFORM_ID = createField(DSL.name("freeform_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.freeform_source_link.source_id</code>.
     */
    public final TableField<FreeformSourceLinkRecord, Long> SOURCE_ID = createField(DSL.name("source_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.freeform_source_link.type</code>.
     */
    public final TableField<FreeformSourceLinkRecord, String> TYPE = createField(DSL.name("type"), org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.freeform_source_link.name</code>.
     */
    public final TableField<FreeformSourceLinkRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.freeform_source_link.value</code>.
     */
    public final TableField<FreeformSourceLinkRecord, String> VALUE = createField(DSL.name("value"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.freeform_source_link.order_by</code>.
     */
    public final TableField<FreeformSourceLinkRecord, Long> ORDER_BY = createField(DSL.name("order_by"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('freeform_source_link_order_by_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * Create a <code>public.freeform_source_link</code> table reference
     */
    public FreeformSourceLink() {
        this(DSL.name("freeform_source_link"), null);
    }

    /**
     * Create an aliased <code>public.freeform_source_link</code> table reference
     */
    public FreeformSourceLink(String alias) {
        this(DSL.name(alias), FREEFORM_SOURCE_LINK);
    }

    /**
     * Create an aliased <code>public.freeform_source_link</code> table reference
     */
    public FreeformSourceLink(Name alias) {
        this(alias, FREEFORM_SOURCE_LINK);
    }

    private FreeformSourceLink(Name alias, Table<FreeformSourceLinkRecord> aliased) {
        this(alias, aliased, null);
    }

    private FreeformSourceLink(Name alias, Table<FreeformSourceLinkRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> FreeformSourceLink(Table<O> child, ForeignKey<O, FreeformSourceLinkRecord> key) {
        super(child, key, FREEFORM_SOURCE_LINK);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FREEFORM_SOURCE_LINK_FREEFORM_ID_IDX, Indexes.FREEFORM_SOURCE_LINK_NAME_IDX, Indexes.FREEFORM_SOURCE_LINK_SOURCE_ID_IDX, Indexes.FREEFORM_SOURCE_LINK_VALUE_IDX);
    }

    @Override
    public Identity<FreeformSourceLinkRecord, Long> getIdentity() {
        return Keys.IDENTITY_FREEFORM_SOURCE_LINK;
    }

    @Override
    public UniqueKey<FreeformSourceLinkRecord> getPrimaryKey() {
        return Keys.FREEFORM_SOURCE_LINK_PKEY;
    }

    @Override
    public List<UniqueKey<FreeformSourceLinkRecord>> getKeys() {
        return Arrays.<UniqueKey<FreeformSourceLinkRecord>>asList(Keys.FREEFORM_SOURCE_LINK_PKEY);
    }

    @Override
    public List<ForeignKey<FreeformSourceLinkRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<FreeformSourceLinkRecord, ?>>asList(Keys.FREEFORM_SOURCE_LINK__FREEFORM_SOURCE_LINK_FREEFORM_ID_FKEY, Keys.FREEFORM_SOURCE_LINK__FREEFORM_SOURCE_LINK_SOURCE_ID_FKEY);
    }

    public Freeform freeform() {
        return new Freeform(this, Keys.FREEFORM_SOURCE_LINK__FREEFORM_SOURCE_LINK_FREEFORM_ID_FKEY);
    }

    public Source source() {
        return new Source(this, Keys.FREEFORM_SOURCE_LINK__FREEFORM_SOURCE_LINK_SOURCE_ID_FKEY);
    }

    @Override
    public FreeformSourceLink as(String alias) {
        return new FreeformSourceLink(DSL.name(alias), this);
    }

    @Override
    public FreeformSourceLink as(Name alias) {
        return new FreeformSourceLink(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FreeformSourceLink rename(String name) {
        return new FreeformSourceLink(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FreeformSourceLink rename(Name name) {
        return new FreeformSourceLink(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, Long, String, String, String, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
