/*
 * This file is generated by jOOQ.
 */
package eki.ekilex.data.db.tables;


import eki.ekilex.data.db.Keys;
import eki.ekilex.data.db.Public;
import eki.ekilex.data.db.tables.records.LabelTypeRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LabelType extends TableImpl<LabelTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.label_type</code>
     */
    public static final LabelType LABEL_TYPE = new LabelType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LabelTypeRecord> getRecordType() {
        return LabelTypeRecord.class;
    }

    /**
     * The column <code>public.label_type.code</code>.
     */
    public final TableField<LabelTypeRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>public.label_type.value</code>.
     */
    public final TableField<LabelTypeRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.CLOB.nullable(false), this, "");

    private LabelType(Name alias, Table<LabelTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private LabelType(Name alias, Table<LabelTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.label_type</code> table reference
     */
    public LabelType(String alias) {
        this(DSL.name(alias), LABEL_TYPE);
    }

    /**
     * Create an aliased <code>public.label_type</code> table reference
     */
    public LabelType(Name alias) {
        this(alias, LABEL_TYPE);
    }

    /**
     * Create a <code>public.label_type</code> table reference
     */
    public LabelType() {
        this(DSL.name("label_type"), null);
    }

    public <O extends Record> LabelType(Table<O> child, ForeignKey<O, LabelTypeRecord> key) {
        super(child, key, LABEL_TYPE);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<LabelTypeRecord> getPrimaryKey() {
        return Keys.LABEL_TYPE_PKEY;
    }

    @Override
    public List<UniqueKey<LabelTypeRecord>> getKeys() {
        return Arrays.<UniqueKey<LabelTypeRecord>>asList(Keys.LABEL_TYPE_PKEY);
    }

    @Override
    public LabelType as(String alias) {
        return new LabelType(DSL.name(alias), this);
    }

    @Override
    public LabelType as(Name alias) {
        return new LabelType(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public LabelType rename(String name) {
        return new LabelType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LabelType rename(Name name) {
        return new LabelType(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
