/*
 * This file is generated by jOOQ.
 */
package eki.ekilex.data.db.tables;


import eki.ekilex.data.db.Public;
import eki.ekilex.data.db.tables.records.ViewWwLexemeSourceLinkRecord;
import eki.ekilex.data.db.udt.records.TypeSourceLinkRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewWwLexemeSourceLink extends TableImpl<ViewWwLexemeSourceLinkRecord> {

    private static final long serialVersionUID = 1048768329;

    /**
     * The reference instance of <code>public.view_ww_lexeme_source_link</code>
     */
    public static final ViewWwLexemeSourceLink VIEW_WW_LEXEME_SOURCE_LINK = new ViewWwLexemeSourceLink();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ViewWwLexemeSourceLinkRecord> getRecordType() {
        return ViewWwLexemeSourceLinkRecord.class;
    }

    /**
     * The column <code>public.view_ww_lexeme_source_link.lexeme_id</code>.
     */
    public final TableField<ViewWwLexemeSourceLinkRecord, Long> LEXEME_ID = createField("lexeme_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.view_ww_lexeme_source_link.source_links</code>.
     */
    public final TableField<ViewWwLexemeSourceLinkRecord, TypeSourceLinkRecord[]> SOURCE_LINKS = createField("source_links", eki.ekilex.data.db.udt.TypeSourceLink.TYPE_SOURCE_LINK.getDataType().getArrayDataType(), this, "");

    /**
     * Create a <code>public.view_ww_lexeme_source_link</code> table reference
     */
    public ViewWwLexemeSourceLink() {
        this(DSL.name("view_ww_lexeme_source_link"), null);
    }

    /**
     * Create an aliased <code>public.view_ww_lexeme_source_link</code> table reference
     */
    public ViewWwLexemeSourceLink(String alias) {
        this(DSL.name(alias), VIEW_WW_LEXEME_SOURCE_LINK);
    }

    /**
     * Create an aliased <code>public.view_ww_lexeme_source_link</code> table reference
     */
    public ViewWwLexemeSourceLink(Name alias) {
        this(alias, VIEW_WW_LEXEME_SOURCE_LINK);
    }

    private ViewWwLexemeSourceLink(Name alias, Table<ViewWwLexemeSourceLinkRecord> aliased) {
        this(alias, aliased, null);
    }

    private ViewWwLexemeSourceLink(Name alias, Table<ViewWwLexemeSourceLinkRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ViewWwLexemeSourceLink(Table<O> child, ForeignKey<O, ViewWwLexemeSourceLinkRecord> key) {
        super(child, key, VIEW_WW_LEXEME_SOURCE_LINK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewWwLexemeSourceLink as(String alias) {
        return new ViewWwLexemeSourceLink(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewWwLexemeSourceLink as(Name alias) {
        return new ViewWwLexemeSourceLink(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewWwLexemeSourceLink rename(String name) {
        return new ViewWwLexemeSourceLink(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewWwLexemeSourceLink rename(Name name) {
        return new ViewWwLexemeSourceLink(name, null);
    }
}
