/*
 * This file is generated by jOOQ.
 */
package eki.wordweb.data.db.tables;


import eki.wordweb.data.db.Indexes;
import eki.wordweb.data.db.Public;
import eki.wordweb.data.db.tables.records.MviewWwLexemeFreeformSourceLinkRecord;
import eki.wordweb.data.db.udt.records.TypeSourceLinkRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MviewWwLexemeFreeformSourceLink extends TableImpl<MviewWwLexemeFreeformSourceLinkRecord> {

    private static final long serialVersionUID = 2091808971;

    /**
     * The reference instance of <code>public.mview_ww_lexeme_freeform_source_link</code>
     */
    public static final MviewWwLexemeFreeformSourceLink MVIEW_WW_LEXEME_FREEFORM_SOURCE_LINK = new MviewWwLexemeFreeformSourceLink();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MviewWwLexemeFreeformSourceLinkRecord> getRecordType() {
        return MviewWwLexemeFreeformSourceLinkRecord.class;
    }

    /**
     * The column <code>public.mview_ww_lexeme_freeform_source_link.lexeme_id</code>.
     */
    public final TableField<MviewWwLexemeFreeformSourceLinkRecord, Long> LEXEME_ID = createField("lexeme_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.mview_ww_lexeme_freeform_source_link.source_links</code>.
     */
    public final TableField<MviewWwLexemeFreeformSourceLinkRecord, TypeSourceLinkRecord[]> SOURCE_LINKS = createField("source_links", eki.wordweb.data.db.udt.TypeSourceLink.TYPE_SOURCE_LINK.getDataType().getArrayDataType(), this, "");

    /**
     * Create a <code>public.mview_ww_lexeme_freeform_source_link</code> table reference
     */
    public MviewWwLexemeFreeformSourceLink() {
        this(DSL.name("mview_ww_lexeme_freeform_source_link"), null);
    }

    /**
     * Create an aliased <code>public.mview_ww_lexeme_freeform_source_link</code> table reference
     */
    public MviewWwLexemeFreeformSourceLink(String alias) {
        this(DSL.name(alias), MVIEW_WW_LEXEME_FREEFORM_SOURCE_LINK);
    }

    /**
     * Create an aliased <code>public.mview_ww_lexeme_freeform_source_link</code> table reference
     */
    public MviewWwLexemeFreeformSourceLink(Name alias) {
        this(alias, MVIEW_WW_LEXEME_FREEFORM_SOURCE_LINK);
    }

    private MviewWwLexemeFreeformSourceLink(Name alias, Table<MviewWwLexemeFreeformSourceLinkRecord> aliased) {
        this(alias, aliased, null);
    }

    private MviewWwLexemeFreeformSourceLink(Name alias, Table<MviewWwLexemeFreeformSourceLinkRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> MviewWwLexemeFreeformSourceLink(Table<O> child, ForeignKey<O, MviewWwLexemeFreeformSourceLinkRecord> key) {
        super(child, key, MVIEW_WW_LEXEME_FREEFORM_SOURCE_LINK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MVIEW_WW_LEXEME_FREEFORM_SOURCE_LINK_WORD_ID_IDX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MviewWwLexemeFreeformSourceLink as(String alias) {
        return new MviewWwLexemeFreeformSourceLink(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MviewWwLexemeFreeformSourceLink as(Name alias) {
        return new MviewWwLexemeFreeformSourceLink(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MviewWwLexemeFreeformSourceLink rename(String name) {
        return new MviewWwLexemeFreeformSourceLink(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MviewWwLexemeFreeformSourceLink rename(Name name) {
        return new MviewWwLexemeFreeformSourceLink(name, null);
    }
}
