/*
 * This file is generated by jOOQ.
 */
package eki.ekilex.data.db.main.tables;


import eki.ekilex.data.db.main.Keys;
import eki.ekilex.data.db.main.Public;
import eki.ekilex.data.db.main.tables.records.ConstructMemberRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConstructMember extends TableImpl<ConstructMemberRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.construct_member</code>
     */
    public static final ConstructMember CONSTRUCT_MEMBER = new ConstructMember();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ConstructMemberRecord> getRecordType() {
        return ConstructMemberRecord.class;
    }

    /**
     * The column <code>public.construct_member.id</code>.
     */
    public final TableField<ConstructMemberRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.construct_member.construct_id</code>.
     */
    public final TableField<ConstructMemberRecord, Long> CONSTRUCT_ID = createField(DSL.name("construct_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.construct_member.cgovernment_code</code>.
     */
    public final TableField<ConstructMemberRecord, String> CGOVERNMENT_CODE = createField(DSL.name("cgovernment_code"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.construct_member.member_role</code>.
     */
    public final TableField<ConstructMemberRecord, String> MEMBER_ROLE = createField(DSL.name("member_role"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.construct_member.semantic_role_code</code>.
     */
    public final TableField<ConstructMemberRecord, String> SEMANTIC_ROLE_CODE = createField(DSL.name("semantic_role_code"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.construct_member.is_head</code>.
     */
    public final TableField<ConstructMemberRecord, Boolean> IS_HEAD = createField(DSL.name("is_head"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field("false", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.construct_member.member_order</code>.
     */
    public final TableField<ConstructMemberRecord, Integer> MEMBER_ORDER = createField(DSL.name("member_order"), SQLDataType.INTEGER.nullable(false), this, "");

    private ConstructMember(Name alias, Table<ConstructMemberRecord> aliased) {
        this(alias, aliased, null);
    }

    private ConstructMember(Name alias, Table<ConstructMemberRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.construct_member</code> table reference
     */
    public ConstructMember(String alias) {
        this(DSL.name(alias), CONSTRUCT_MEMBER);
    }

    /**
     * Create an aliased <code>public.construct_member</code> table reference
     */
    public ConstructMember(Name alias) {
        this(alias, CONSTRUCT_MEMBER);
    }

    /**
     * Create a <code>public.construct_member</code> table reference
     */
    public ConstructMember() {
        this(DSL.name("construct_member"), null);
    }

    public <O extends Record> ConstructMember(Table<O> child, ForeignKey<O, ConstructMemberRecord> key) {
        super(child, key, CONSTRUCT_MEMBER);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<ConstructMemberRecord, Long> getIdentity() {
        return (Identity<ConstructMemberRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ConstructMemberRecord> getPrimaryKey() {
        return Keys.CONSTRUCT_MEMBER_PKEY;
    }

    @Override
    public List<UniqueKey<ConstructMemberRecord>> getKeys() {
        return Arrays.<UniqueKey<ConstructMemberRecord>>asList(Keys.CONSTRUCT_MEMBER_PKEY);
    }

    @Override
    public List<ForeignKey<ConstructMemberRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ConstructMemberRecord, ?>>asList(Keys.CONSTRUCT_MEMBER__CONSTRUCT_MEMBER_CONSTRUCT_ID_FKEY, Keys.CONSTRUCT_MEMBER__CONSTRUCT_MEMBER_CGOVERNMENT_CODE_FKEY, Keys.CONSTRUCT_MEMBER__CONSTRUCT_MEMBER_SEMANTIC_ROLE_CODE_FKEY);
    }

    private transient Construct _construct;
    private transient Cgovernment _cgovernment;
    private transient SemanticRole _semanticRole;

    public Construct construct() {
        if (_construct == null)
            _construct = new Construct(this, Keys.CONSTRUCT_MEMBER__CONSTRUCT_MEMBER_CONSTRUCT_ID_FKEY);

        return _construct;
    }

    public Cgovernment cgovernment() {
        if (_cgovernment == null)
            _cgovernment = new Cgovernment(this, Keys.CONSTRUCT_MEMBER__CONSTRUCT_MEMBER_CGOVERNMENT_CODE_FKEY);

        return _cgovernment;
    }

    public SemanticRole semanticRole() {
        if (_semanticRole == null)
            _semanticRole = new SemanticRole(this, Keys.CONSTRUCT_MEMBER__CONSTRUCT_MEMBER_SEMANTIC_ROLE_CODE_FKEY);

        return _semanticRole;
    }

    @Override
    public ConstructMember as(String alias) {
        return new ConstructMember(DSL.name(alias), this);
    }

    @Override
    public ConstructMember as(Name alias) {
        return new ConstructMember(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ConstructMember rename(String name) {
        return new ConstructMember(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ConstructMember rename(Name name) {
        return new ConstructMember(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, String, String, String, Boolean, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
