/*
 * This file is generated by jOOQ.
 */
package eki.ekilex.data.db.main.tables;


import eki.ekilex.data.db.main.Keys;
import eki.ekilex.data.db.main.Public;
import eki.ekilex.data.db.main.tables.records.ConstructMemberPosGroupRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConstructMemberPosGroup extends TableImpl<ConstructMemberPosGroupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.construct_member_pos_group</code>
     */
    public static final ConstructMemberPosGroup CONSTRUCT_MEMBER_POS_GROUP = new ConstructMemberPosGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ConstructMemberPosGroupRecord> getRecordType() {
        return ConstructMemberPosGroupRecord.class;
    }

    /**
     * The column <code>public.construct_member_pos_group.id</code>.
     */
    public final TableField<ConstructMemberPosGroupRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.construct_member_pos_group.construct_member_id</code>.
     */
    public final TableField<ConstructMemberPosGroupRecord, Long> CONSTRUCT_MEMBER_ID = createField(DSL.name("construct_member_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.construct_member_pos_group.pos_group_code</code>.
     */
    public final TableField<ConstructMemberPosGroupRecord, String> POS_GROUP_CODE = createField(DSL.name("pos_group_code"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.construct_member_pos_group.order_by</code>.
     */
    public final TableField<ConstructMemberPosGroupRecord, Long> ORDER_BY = createField(DSL.name("order_by"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    private ConstructMemberPosGroup(Name alias, Table<ConstructMemberPosGroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private ConstructMemberPosGroup(Name alias, Table<ConstructMemberPosGroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.construct_member_pos_group</code> table reference
     */
    public ConstructMemberPosGroup(String alias) {
        this(DSL.name(alias), CONSTRUCT_MEMBER_POS_GROUP);
    }

    /**
     * Create an aliased <code>public.construct_member_pos_group</code> table reference
     */
    public ConstructMemberPosGroup(Name alias) {
        this(alias, CONSTRUCT_MEMBER_POS_GROUP);
    }

    /**
     * Create a <code>public.construct_member_pos_group</code> table reference
     */
    public ConstructMemberPosGroup() {
        this(DSL.name("construct_member_pos_group"), null);
    }

    public <O extends Record> ConstructMemberPosGroup(Table<O> child, ForeignKey<O, ConstructMemberPosGroupRecord> key) {
        super(child, key, CONSTRUCT_MEMBER_POS_GROUP);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<ConstructMemberPosGroupRecord, Long> getIdentity() {
        return (Identity<ConstructMemberPosGroupRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ConstructMemberPosGroupRecord> getPrimaryKey() {
        return Keys.CONSTRUCT_MEMBER_POS_GROUP_PKEY;
    }

    @Override
    public List<UniqueKey<ConstructMemberPosGroupRecord>> getKeys() {
        return Arrays.<UniqueKey<ConstructMemberPosGroupRecord>>asList(Keys.CONSTRUCT_MEMBER_POS_GROUP_PKEY, Keys.CONSTRUCT_MEMBER_POS_GROUP_CONSTRUCT_MEMBER_ID_POS_GROUP_CO_KEY);
    }

    @Override
    public List<ForeignKey<ConstructMemberPosGroupRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ConstructMemberPosGroupRecord, ?>>asList(Keys.CONSTRUCT_MEMBER_POS_GROUP__CONSTRUCT_MEMBER_POS_GROUP_CONSTRUCT_MEMBER_ID_FKEY, Keys.CONSTRUCT_MEMBER_POS_GROUP__CONSTRUCT_MEMBER_POS_GROUP_POS_GROUP_CODE_FKEY);
    }

    private transient ConstructMember _constructMember;
    private transient PosGroup _posGroup;

    public ConstructMember constructMember() {
        if (_constructMember == null)
            _constructMember = new ConstructMember(this, Keys.CONSTRUCT_MEMBER_POS_GROUP__CONSTRUCT_MEMBER_POS_GROUP_CONSTRUCT_MEMBER_ID_FKEY);

        return _constructMember;
    }

    public PosGroup posGroup() {
        if (_posGroup == null)
            _posGroup = new PosGroup(this, Keys.CONSTRUCT_MEMBER_POS_GROUP__CONSTRUCT_MEMBER_POS_GROUP_POS_GROUP_CODE_FKEY);

        return _posGroup;
    }

    @Override
    public ConstructMemberPosGroup as(String alias) {
        return new ConstructMemberPosGroup(DSL.name(alias), this);
    }

    @Override
    public ConstructMemberPosGroup as(Name alias) {
        return new ConstructMemberPosGroup(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ConstructMemberPosGroup rename(String name) {
        return new ConstructMemberPosGroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ConstructMemberPosGroup rename(Name name) {
        return new ConstructMemberPosGroup(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, String, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
