/*
 * This file is generated by jOOQ.
 */
package eki.ekilex.data.db.main.tables;


import eki.ekilex.data.db.main.Keys;
import eki.ekilex.data.db.main.Public;
import eki.ekilex.data.db.main.tables.records.DefinitionTypeLabelRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefinitionTypeLabel extends TableImpl<DefinitionTypeLabelRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.definition_type_label</code>
     */
    public static final DefinitionTypeLabel DEFINITION_TYPE_LABEL = new DefinitionTypeLabel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DefinitionTypeLabelRecord> getRecordType() {
        return DefinitionTypeLabelRecord.class;
    }

    /**
     * The column <code>public.definition_type_label.code</code>.
     */
    public final TableField<DefinitionTypeLabelRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.definition_type_label.value</code>.
     */
    public final TableField<DefinitionTypeLabelRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.definition_type_label.lang</code>.
     */
    public final TableField<DefinitionTypeLabelRecord, String> LANG = createField(DSL.name("lang"), SQLDataType.CHAR(3).nullable(false), this, "");

    /**
     * The column <code>public.definition_type_label.type</code>.
     */
    public final TableField<DefinitionTypeLabelRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    private DefinitionTypeLabel(Name alias, Table<DefinitionTypeLabelRecord> aliased) {
        this(alias, aliased, null);
    }

    private DefinitionTypeLabel(Name alias, Table<DefinitionTypeLabelRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.definition_type_label</code> table reference
     */
    public DefinitionTypeLabel(String alias) {
        this(DSL.name(alias), DEFINITION_TYPE_LABEL);
    }

    /**
     * Create an aliased <code>public.definition_type_label</code> table reference
     */
    public DefinitionTypeLabel(Name alias) {
        this(alias, DEFINITION_TYPE_LABEL);
    }

    /**
     * Create a <code>public.definition_type_label</code> table reference
     */
    public DefinitionTypeLabel() {
        this(DSL.name("definition_type_label"), null);
    }

    public <O extends Record> DefinitionTypeLabel(Table<O> child, ForeignKey<O, DefinitionTypeLabelRecord> key) {
        super(child, key, DEFINITION_TYPE_LABEL);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<UniqueKey<DefinitionTypeLabelRecord>> getKeys() {
        return Arrays.<UniqueKey<DefinitionTypeLabelRecord>>asList(Keys.DEFINITION_TYPE_LABEL_CODE_LANG_TYPE_KEY);
    }

    @Override
    public List<ForeignKey<DefinitionTypeLabelRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DefinitionTypeLabelRecord, ?>>asList(Keys.DEFINITION_TYPE_LABEL__DEFINITION_TYPE_LABEL_CODE_FKEY, Keys.DEFINITION_TYPE_LABEL__DEFINITION_TYPE_LABEL_LANG_FKEY, Keys.DEFINITION_TYPE_LABEL__DEFINITION_TYPE_LABEL_TYPE_FKEY);
    }

    private transient DefinitionType _definitionType;
    private transient Language _language;
    private transient LabelType _labelType;

    public DefinitionType definitionType() {
        if (_definitionType == null)
            _definitionType = new DefinitionType(this, Keys.DEFINITION_TYPE_LABEL__DEFINITION_TYPE_LABEL_CODE_FKEY);

        return _definitionType;
    }

    public Language language() {
        if (_language == null)
            _language = new Language(this, Keys.DEFINITION_TYPE_LABEL__DEFINITION_TYPE_LABEL_LANG_FKEY);

        return _language;
    }

    public LabelType labelType() {
        if (_labelType == null)
            _labelType = new LabelType(this, Keys.DEFINITION_TYPE_LABEL__DEFINITION_TYPE_LABEL_TYPE_FKEY);

        return _labelType;
    }

    @Override
    public DefinitionTypeLabel as(String alias) {
        return new DefinitionTypeLabel(DSL.name(alias), this);
    }

    @Override
    public DefinitionTypeLabel as(Name alias) {
        return new DefinitionTypeLabel(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DefinitionTypeLabel rename(String name) {
        return new DefinitionTypeLabel(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DefinitionTypeLabel rename(Name name) {
        return new DefinitionTypeLabel(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
