/*
 * This file is generated by jOOQ.
 */
package eki.ekilex.data.db.main.tables;


import eki.ekilex.data.db.main.Keys;
import eki.ekilex.data.db.main.Public;
import eki.ekilex.data.db.main.tables.records.SentenceMemberRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SentenceMember extends TableImpl<SentenceMemberRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.sentence_member</code>
     */
    public static final SentenceMember SENTENCE_MEMBER = new SentenceMember();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SentenceMemberRecord> getRecordType() {
        return SentenceMemberRecord.class;
    }

    /**
     * The column <code>public.sentence_member.id</code>.
     */
    public final TableField<SentenceMemberRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.sentence_member.sentence_id</code>.
     */
    public final TableField<SentenceMemberRecord, Long> SENTENCE_ID = createField(DSL.name("sentence_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.sentence_member.construct_member_id</code>.
     */
    public final TableField<SentenceMemberRecord, Long> CONSTRUCT_MEMBER_ID = createField(DSL.name("construct_member_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.sentence_member.value</code>.
     */
    public final TableField<SentenceMemberRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.sentence_member.member_sentence_id</code>.
     */
    public final TableField<SentenceMemberRecord, Long> MEMBER_SENTENCE_ID = createField(DSL.name("member_sentence_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.sentence_member.member_lexeme_id</code>.
     */
    public final TableField<SentenceMemberRecord, Long> MEMBER_LEXEME_ID = createField(DSL.name("member_lexeme_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.sentence_member.member_form_id</code>.
     */
    public final TableField<SentenceMemberRecord, Long> MEMBER_FORM_ID = createField(DSL.name("member_form_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.sentence_member.pos_group_code</code>.
     */
    public final TableField<SentenceMemberRecord, String> POS_GROUP_CODE = createField(DSL.name("pos_group_code"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.sentence_member.deprel_code</code>.
     */
    public final TableField<SentenceMemberRecord, String> DEPREL_CODE = createField(DSL.name("deprel_code"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.sentence_member.member_role</code>.
     */
    public final TableField<SentenceMemberRecord, String> MEMBER_ROLE = createField(DSL.name("member_role"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.sentence_member.member_order</code>.
     */
    public final TableField<SentenceMemberRecord, Integer> MEMBER_ORDER = createField(DSL.name("member_order"), SQLDataType.INTEGER.nullable(false), this, "");

    private SentenceMember(Name alias, Table<SentenceMemberRecord> aliased) {
        this(alias, aliased, null);
    }

    private SentenceMember(Name alias, Table<SentenceMemberRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.sentence_member</code> table reference
     */
    public SentenceMember(String alias) {
        this(DSL.name(alias), SENTENCE_MEMBER);
    }

    /**
     * Create an aliased <code>public.sentence_member</code> table reference
     */
    public SentenceMember(Name alias) {
        this(alias, SENTENCE_MEMBER);
    }

    /**
     * Create a <code>public.sentence_member</code> table reference
     */
    public SentenceMember() {
        this(DSL.name("sentence_member"), null);
    }

    public <O extends Record> SentenceMember(Table<O> child, ForeignKey<O, SentenceMemberRecord> key) {
        super(child, key, SENTENCE_MEMBER);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<SentenceMemberRecord, Long> getIdentity() {
        return (Identity<SentenceMemberRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SentenceMemberRecord> getPrimaryKey() {
        return Keys.SENTENCE_MEMBER_PKEY;
    }

    @Override
    public List<UniqueKey<SentenceMemberRecord>> getKeys() {
        return Arrays.<UniqueKey<SentenceMemberRecord>>asList(Keys.SENTENCE_MEMBER_PKEY);
    }

    @Override
    public List<ForeignKey<SentenceMemberRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SentenceMemberRecord, ?>>asList(Keys.SENTENCE_MEMBER__SENTENCE_MEMBER_SENTENCE_ID_FKEY, Keys.SENTENCE_MEMBER__SENTENCE_MEMBER_CONSTRUCT_MEMBER_ID_FKEY, Keys.SENTENCE_MEMBER__SENTENCE_MEMBER_MEMBER_SENTENCE_ID_FKEY, Keys.SENTENCE_MEMBER__SENTENCE_MEMBER_MEMBER_LEXEME_ID_FKEY, Keys.SENTENCE_MEMBER__SENTENCE_MEMBER_MEMBER_FORM_ID_FKEY, Keys.SENTENCE_MEMBER__SENTENCE_MEMBER_POS_GROUP_CODE_FKEY, Keys.SENTENCE_MEMBER__SENTENCE_MEMBER_DEPREL_CODE_FKEY);
    }

    private transient Sentence _sentenceMemberSentenceIdFkey;
    private transient ConstructMember _constructMember;
    private transient Sentence _sentenceMemberMemberSentenceIdFkey;
    private transient Lexeme _lexeme;
    private transient Form _form;
    private transient PosGroup _posGroup;
    private transient Deprel _deprel;

    public Sentence sentenceMemberSentenceIdFkey() {
        if (_sentenceMemberSentenceIdFkey == null)
            _sentenceMemberSentenceIdFkey = new Sentence(this, Keys.SENTENCE_MEMBER__SENTENCE_MEMBER_SENTENCE_ID_FKEY);

        return _sentenceMemberSentenceIdFkey;
    }

    public ConstructMember constructMember() {
        if (_constructMember == null)
            _constructMember = new ConstructMember(this, Keys.SENTENCE_MEMBER__SENTENCE_MEMBER_CONSTRUCT_MEMBER_ID_FKEY);

        return _constructMember;
    }

    public Sentence sentenceMemberMemberSentenceIdFkey() {
        if (_sentenceMemberMemberSentenceIdFkey == null)
            _sentenceMemberMemberSentenceIdFkey = new Sentence(this, Keys.SENTENCE_MEMBER__SENTENCE_MEMBER_MEMBER_SENTENCE_ID_FKEY);

        return _sentenceMemberMemberSentenceIdFkey;
    }

    public Lexeme lexeme() {
        if (_lexeme == null)
            _lexeme = new Lexeme(this, Keys.SENTENCE_MEMBER__SENTENCE_MEMBER_MEMBER_LEXEME_ID_FKEY);

        return _lexeme;
    }

    public Form form() {
        if (_form == null)
            _form = new Form(this, Keys.SENTENCE_MEMBER__SENTENCE_MEMBER_MEMBER_FORM_ID_FKEY);

        return _form;
    }

    public PosGroup posGroup() {
        if (_posGroup == null)
            _posGroup = new PosGroup(this, Keys.SENTENCE_MEMBER__SENTENCE_MEMBER_POS_GROUP_CODE_FKEY);

        return _posGroup;
    }

    public Deprel deprel() {
        if (_deprel == null)
            _deprel = new Deprel(this, Keys.SENTENCE_MEMBER__SENTENCE_MEMBER_DEPREL_CODE_FKEY);

        return _deprel;
    }

    @Override
    public SentenceMember as(String alias) {
        return new SentenceMember(DSL.name(alias), this);
    }

    @Override
    public SentenceMember as(Name alias) {
        return new SentenceMember(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SentenceMember rename(String name) {
        return new SentenceMember(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SentenceMember rename(Name name) {
        return new SentenceMember(name, null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, Long, Long, String, Long, Long, Long, String, String, String, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }
}
