/*
 * This file is generated by jOOQ.
 */
package eki.ekilex.data.db.main.tables;


import eki.ekilex.data.db.main.Keys;
import eki.ekilex.data.db.main.Public;
import eki.ekilex.data.db.main.tables.records.WordEtymCommentRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WordEtymComment extends TableImpl<WordEtymCommentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.word_etym_comment</code>
     */
    public static final WordEtymComment WORD_ETYM_COMMENT = new WordEtymComment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WordEtymCommentRecord> getRecordType() {
        return WordEtymCommentRecord.class;
    }

    /**
     * The column <code>public.word_etym_comment.id</code>.
     */
    public final TableField<WordEtymCommentRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.word_etym_comment.word_etym_id</code>.
     */
    public final TableField<WordEtymCommentRecord, Long> WORD_ETYM_ID = createField(DSL.name("word_etym_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.word_etym_comment.value</code>.
     */
    public final TableField<WordEtymCommentRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.word_etym_comment.value_prese</code>.
     */
    public final TableField<WordEtymCommentRecord, String> VALUE_PRESE = createField(DSL.name("value_prese"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.word_etym_comment.orig_name</code>.
     */
    public final TableField<WordEtymCommentRecord, String> ORIG_NAME = createField(DSL.name("orig_name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.word_etym_comment.order_by</code>.
     */
    public final TableField<WordEtymCommentRecord, Long> ORDER_BY = createField(DSL.name("order_by"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    private WordEtymComment(Name alias, Table<WordEtymCommentRecord> aliased) {
        this(alias, aliased, null);
    }

    private WordEtymComment(Name alias, Table<WordEtymCommentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.word_etym_comment</code> table reference
     */
    public WordEtymComment(String alias) {
        this(DSL.name(alias), WORD_ETYM_COMMENT);
    }

    /**
     * Create an aliased <code>public.word_etym_comment</code> table reference
     */
    public WordEtymComment(Name alias) {
        this(alias, WORD_ETYM_COMMENT);
    }

    /**
     * Create a <code>public.word_etym_comment</code> table reference
     */
    public WordEtymComment() {
        this(DSL.name("word_etym_comment"), null);
    }

    public <O extends Record> WordEtymComment(Table<O> child, ForeignKey<O, WordEtymCommentRecord> key) {
        super(child, key, WORD_ETYM_COMMENT);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<WordEtymCommentRecord, Long> getIdentity() {
        return (Identity<WordEtymCommentRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<WordEtymCommentRecord> getPrimaryKey() {
        return Keys.WORD_ETYM_COMMENT_PKEY;
    }

    @Override
    public List<UniqueKey<WordEtymCommentRecord>> getKeys() {
        return Arrays.<UniqueKey<WordEtymCommentRecord>>asList(Keys.WORD_ETYM_COMMENT_PKEY);
    }

    @Override
    public List<ForeignKey<WordEtymCommentRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<WordEtymCommentRecord, ?>>asList(Keys.WORD_ETYM_COMMENT__WORD_ETYM_COMMENT_WORD_ETYM_ID_FKEY);
    }

    private transient WordEtym _wordEtym;

    public WordEtym wordEtym() {
        if (_wordEtym == null)
            _wordEtym = new WordEtym(this, Keys.WORD_ETYM_COMMENT__WORD_ETYM_COMMENT_WORD_ETYM_ID_FKEY);

        return _wordEtym;
    }

    @Override
    public WordEtymComment as(String alias) {
        return new WordEtymComment(DSL.name(alias), this);
    }

    @Override
    public WordEtymComment as(Name alias) {
        return new WordEtymComment(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WordEtymComment rename(String name) {
        return new WordEtymComment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WordEtymComment rename(Name name) {
        return new WordEtymComment(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, String, String, String, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
