insert into aspect_type (code, datasets) values ('sov', '{}');
insert into aspect_type (code, datasets) values ('nesov', '{}');
insert into aspect_type (code, datasets) values ('sov/nesov', '{}');
insert into deriv (code, datasets) values ('adv', '{}');
insert into deriv (code, datasets) values ('dem', '{}');
insert into deriv (code, datasets) values ('komp', '{}');
insert into deriv (code, datasets) values ('superl', '{}');
insert into deriv (code, datasets) values ('tgn', '{}');
insert into deriv (code, datasets) values ('tn', '{}');
insert into deriv (code, datasets) values ('as', '{}');
insert into deriv (code, datasets) values ('posit', '{}');
insert into deriv (code, datasets) values ('ssv', '{}');
insert into display_morph (code, datasets) values ('keskv', '{}');
insert into display_morph (code, datasets) values ('üliv', '{}');
insert into display_morph (code, datasets) values ('ips', '{}');
insert into display_morph (code, datasets) values ('ipf', '{}');
insert into display_morph (code, datasets) values ('pts', '{}');
insert into display_morph (code, datasets) values ('pl', '{}');
insert into display_morph (code, datasets) values ('sg', '{}');
insert into display_morph (code, datasets) values ('Ipf', '{}');
insert into display_morph (code, datasets) values ('Sg', '{}');
insert into display_morph (code, datasets) values ('Pl', '{}');
insert into display_morph (code, datasets) values ('Ips', '{}');
insert into display_morph (code, datasets) values ('Pts', '{}');
insert into etymology_type (code, datasets) values ('kirjakeele sõna', '{}');
insert into etymology_type (code, datasets) values ('kõlasõna', '{}');
insert into etymology_type (code, datasets) values ('laensõna', '{}');
insert into etymology_type (code, datasets) values ('laenväljend', '{}');
insert into etymology_type (code, datasets) values ('pooltõlkelaen', '{}');
insert into etymology_type (code, datasets) values ('tehissõna', '{}');
insert into etymology_type (code, datasets) values ('tootenimi', '{}');
insert into etymology_type (code, datasets) values ('tõlkelaen', '{}');
insert into form_rel_type (code, datasets) values ('mvt', '{}');
insert into gender (code, datasets) values ('f', '{}');
insert into gender (code, datasets) values ('n', '{}');
insert into gender (code, datasets) values ('o', '{}');
insert into gender (code, datasets) values ('m', '{}');
insert into government_type (code, datasets) values ('obj', '{}');
insert into government_type (code, datasets) values ('kn', '{}');
insert into government_type (code, datasets) values ('ks', '{}');
insert into government_type (code, datasets) values ('yld', '{}');
insert into government_type (code, datasets) values ('inf', '{}');
insert into government_type (code, datasets) values ('kla', '{}');
insert into government_type (code, datasets) values ('subj', '{}');
insert into lex_rel_type (code, datasets) values ('comp', '{}');
insert into lex_rel_type (code, datasets) values ('head', '{}');
insert into lex_rel_type (code, datasets) values ('vor', '{}');
insert into lex_rel_type (code, datasets) values ('yvr', '{}');
insert into lex_rel_type (code, datasets) values ('pyh', '{}');
insert into lex_rel_type (code, datasets) values ('yhvt', '{}');
insert into lex_rel_type (code, datasets) values ('tvt:vrd', '{}');
insert into lex_rel_type (code, datasets) values ('tvt:vt ka', '{}');
insert into lex_rel_type (code, datasets) values ('yvt:vrd', '{}');
insert into lex_rel_type (code, datasets) values ('yvt:vt ka', '{}');
insert into lex_rel_type (code, datasets) values ('yvt:NB', '{}');
insert into lex_rel_type (code, datasets) values ('lyh', '{}');
insert into lex_rel_type (code, datasets) values ('mm', '{}');
insert into lexeme_frequency (code, datasets) values ('1', '{}');
insert into lexeme_frequency (code, datasets) values ('2', '{}');
insert into lexeme_frequency (code, datasets) values ('3', '{}');
insert into lexeme_frequency (code, datasets) values ('4', '{}');
insert into lexeme_frequency (code, datasets) values ('F0', '{}');
insert into lexeme_frequency (code, datasets) values ('F1', '{}');
insert into lexeme_frequency (code, datasets) values ('F2', '{}');
insert into lexeme_frequency (code, datasets) values ('F3', '{}');
insert into lexeme_frequency (code, datasets) values ('F4', '{}');
insert into lexeme_frequency (code, datasets) values ('F5', '{}');
insert into lexeme_frequency (code, datasets) values ('L2', '{}');
insert into lexeme_frequency (code, datasets) values ('L3', '{}');
insert into lexeme_frequency (code, datasets) values ('L4', '{}');
insert into meaning_rel_type (code, datasets) values ('ant', '{}');
insert into meaning_rel_type (code, datasets) values ('cohyponym', '{}');
insert into morph (code, datasets) values ('ID', '{}');
insert into morph (code, datasets) values ('SgN', '{}');
insert into morph (code, datasets) values ('SgG', '{}');
insert into morph (code, datasets) values ('SgP', '{}');
insert into morph (code, datasets) values ('SgAdt', '{}');
insert into morph (code, datasets) values ('SgIll', '{}');
insert into morph (code, datasets) values ('SgIn', '{}');
insert into morph (code, datasets) values ('SgEl', '{}');
insert into morph (code, datasets) values ('SgAll', '{}');
insert into morph (code, datasets) values ('SgAd', '{}');
insert into morph (code, datasets) values ('SgAbl', '{}');
insert into morph (code, datasets) values ('SgTr', '{}');
insert into morph (code, datasets) values ('SgTer', '{}');
insert into morph (code, datasets) values ('SgEs', '{}');
insert into morph (code, datasets) values ('SgAb', '{}');
insert into morph (code, datasets) values ('SgKom', '{}');
insert into morph (code, datasets) values ('PlN', '{}');
insert into morph (code, datasets) values ('PlG', '{}');
insert into morph (code, datasets) values ('PlP', '{}');
insert into morph (code, datasets) values ('PlAdt', '{}');
insert into morph (code, datasets) values ('PlIll', '{}');
insert into morph (code, datasets) values ('PlIn', '{}');
insert into morph (code, datasets) values ('PlEl', '{}');
insert into morph (code, datasets) values ('PlAll', '{}');
insert into morph (code, datasets) values ('PlAd', '{}');
insert into morph (code, datasets) values ('PlAbl', '{}');
insert into morph (code, datasets) values ('PlTr', '{}');
insert into morph (code, datasets) values ('PlTer', '{}');
insert into morph (code, datasets) values ('PlEs', '{}');
insert into morph (code, datasets) values ('PlAb', '{}');
insert into morph (code, datasets) values ('PlKom', '{}');
insert into morph (code, datasets) values ('Sup', '{}');
insert into morph (code, datasets) values ('Inf', '{}');
insert into morph (code, datasets) values ('IndPrSg3', '{}');
insert into morph (code, datasets) values ('IndPrPl1', '{}');
insert into morph (code, datasets) values ('PtsPtIps', '{}');
insert into morph (code, datasets) values ('IndIpfSg3', '{}');
insert into morph (code, datasets) values ('PtsPtPs', '{}');
insert into morph (code, datasets) values ('ImpPrPl2', '{}');
insert into morph (code, datasets) values ('IndPrIps', '{}');
insert into morph (code, datasets) values ('PtsPrIps', '{}');
insert into morph (code, datasets) values ('IndPrPsN', '{}');
insert into morph (code, datasets) values ('IndIpfPsN', '{}');
insert into morph (code, datasets) values ('Neg', '{}');
insert into morph (code, datasets) values ('ImpPrSg2N', '{}');
insert into morph (code, datasets) values ('ImpPrPl2N', '{}');
insert into morph (code, datasets) values ('ImpPrPl1N', '{}');
insert into morph (code, datasets) values ('ImpPrN', '{}');
insert into morph (code, datasets) values ('??', '{}');
insert into morph (code, datasets) values ('Rpl', '{}');
insert into morph (code, datasets) values ('Nlyhi', '{}');
insert into morph (code, datasets) values ('Nvahe', '{}');
insert into morph (code, datasets) values ('SupAb', '{}');
insert into morph (code, datasets) values ('SupIn', '{}');
insert into morph (code, datasets) values ('SupEl', '{}');
insert into morph (code, datasets) values ('SupTr', '{}');
insert into morph (code, datasets) values ('SupIps', '{}');
insert into morph (code, datasets) values ('Ger', '{}');
insert into morph (code, datasets) values ('PtsPrPs', '{}');
insert into morph (code, datasets) values ('IndPrSg1', '{}');
insert into morph (code, datasets) values ('IndPrSg2', '{}');
insert into morph (code, datasets) values ('IndPrPl2', '{}');
insert into morph (code, datasets) values ('IndPrPl3', '{}');
insert into morph (code, datasets) values ('IndPrPs_', '{}');
insert into morph (code, datasets) values ('IndPrIps_', '{}');
insert into morph (code, datasets) values ('IndIpfSg1', '{}');
insert into morph (code, datasets) values ('IndIpfSg2', '{}');
insert into morph (code, datasets) values ('IndIpfPl1', '{}');
insert into morph (code, datasets) values ('IndIpfPl2', '{}');
insert into morph (code, datasets) values ('IndIpfPl3', '{}');
insert into morph (code, datasets) values ('IndIpfIps', '{}');
insert into morph (code, datasets) values ('KndPrSg1', '{}');
insert into morph (code, datasets) values ('KndPrSg2', '{}');
insert into morph (code, datasets) values ('KndPrPs', '{}');
insert into morph (code, datasets) values ('KndPrPl1', '{}');
insert into morph (code, datasets) values ('KndPrPl2', '{}');
insert into morph (code, datasets) values ('KndPrPl3', '{}');
insert into morph (code, datasets) values ('KndPrIps', '{}');
insert into morph (code, datasets) values ('KndPtSg1', '{}');
insert into morph (code, datasets) values ('KndPtSg2', '{}');
insert into morph (code, datasets) values ('KndPtPs', '{}');
insert into morph (code, datasets) values ('KndPtPl1', '{}');
insert into morph (code, datasets) values ('KndPtPl2', '{}');
insert into morph (code, datasets) values ('KndPtPl3', '{}');
insert into morph (code, datasets) values ('KndPtIps', '{}');
insert into morph (code, datasets) values ('KvtPrPs', '{}');
insert into morph (code, datasets) values ('KvtPrIps', '{}');
insert into morph (code, datasets) values ('KvtPtPs', '{}');
insert into morph (code, datasets) values ('KvtPtIps', '{}');
insert into morph (code, datasets) values ('ImpPrSg2', '{}');
insert into morph (code, datasets) values ('ImpPrPl1', '{}');
insert into morph (code, datasets) values ('ImpPrPs', '{}');
insert into morph (code, datasets) values ('ImpPrIps', '{}');
insert into morph (code, datasets) values ('Vlyhi', '{}');
insert into morph (code, datasets) values ('Vvahe', '{}');
insert into morph (code, datasets) values ('IndPrIpsN', '{}');
insert into morph (code, datasets) values ('IndIpfIpsN', '{}');
insert into morph (code, datasets) values ('KvtPrPsN', '{}');
insert into morph (code, datasets) values ('KvtPtPsN', '{}');
insert into morph (code, datasets) values ('KndPrPsN', '{}');
insert into morph (code, datasets) values ('KndPtPsN', '{}');
insert into pos (code, datasets) values ('adj', '{}');
insert into pos (code, datasets) values ('adv', '{}');
insert into pos (code, datasets) values ('adjg', '{}');
insert into pos (code, datasets) values ('prop', '{}');
insert into pos (code, datasets) values ('interj', '{}');
insert into pos (code, datasets) values ('konj', '{}');
insert into pos (code, datasets) values ('adp', '{}');
insert into pos (code, datasets) values ('num', '{}');
insert into pos (code, datasets) values ('ord', '{}');
insert into pos (code, datasets) values ('pron', '{}');
insert into pos (code, datasets) values ('s', '{}');
insert into pos (code, datasets) values ('v', '{}');
insert into pos (code, datasets) values ('x', '{}');
insert into pos (code, datasets) values ('postp', '{}');
insert into pos (code, datasets) values ('prep', '{}');
insert into pos_group (code, datasets) values ('A', '{}');
insert into pos_group (code, datasets) values ('D', '{}');
insert into pos_group (code, datasets) values ('H', '{}');
insert into pos_group (code, datasets) values ('K', '{}');
insert into pos_group (code, datasets) values ('N', '{}');
insert into pos_group (code, datasets) values ('S', '{}');
insert into pos_group (code, datasets) values ('V', '{}');
insert into process_state (code, datasets) values ('määramata', '{}');
insert into process_state (code, datasets) values ('koostamisel', '{}');
insert into process_state (code, datasets) values ('koostatud', '{}');
insert into process_state (code, datasets) values ('ajakohastamisel', '{}');
insert into process_state (code, datasets) values ('ajakohastatud', '{}');
insert into process_state (code, datasets) values ('vajab konsulteerimist', '{}');
insert into process_state (code, datasets) values ('saadetud konsulteerimisele', '{}');
insert into process_state (code, datasets) values ('konsulteerimisel', '{}');
insert into process_state (code, datasets) values ('heaks kiidetud', '{}');
insert into process_state (code, datasets) values ('tagasi lükatud', '{}');
insert into process_state (code, datasets) values ('lahenduseta', '{}');
insert into process_state (code, datasets) values ('toimetamisel', '{}');
insert into process_state (code, datasets) values ('toimetatud', '{}');
insert into process_state (code, datasets) values ('peatoimetamisel', '{}');
insert into process_state (code, datasets) values ('peatoimetatud', '{}');
insert into process_state (code, datasets) values ('valmis', '{}');
insert into process_state (code, datasets) values ('avalik', '{}');
insert into process_state (code, datasets) values ('arhiveeritud', '{}');
insert into process_state (code, datasets) values ('töös', '{}');
insert into process_state (code, datasets) values ('läbi vaatamata', '{}');
insert into process_state (code, datasets) values ('kustutatud', '{}');
insert into register (code, datasets) values ('eevn', '{}');
insert into register (code, datasets) values ('hlv', '{}');
insert into register (code, datasets) values ('hellitl', '{}');
insert into register (code, datasets) values ('hrv', '{}');
insert into register (code, datasets) values ('kõrgst', '{}');
insert into register (code, datasets) values ('lastek', '{}');
insert into register (code, datasets) values ('luulek', '{}');
insert into register (code, datasets) values ('madalk', '{}');
insert into register (code, datasets) values ('murd', '{}');
insert into register (code, datasets) values ('nlj', '{}');
insert into register (code, datasets) values ('piltl', '{}');
insert into register (code, datasets) values ('släng', '{}');
insert into register (code, datasets) values ('uudis', '{}');
insert into register (code, datasets) values ('kõnek', '{}');
insert into register (code, datasets) values ('van', '{}');
insert into register (code, datasets) values ('vulg', '{}');
insert into usage_type (code, datasets) values ('ls', '{}');
insert into usage_type (code, datasets) values ('Vs', '{}');
insert into usage_type (code, datasets) values ('y', '{}');
insert into value_state (code, datasets) values ('eelistermin', '{}');
insert into value_state (code, datasets) values ('rööptermin', '{}');
insert into value_state (code, datasets) values ('variant', '{}');
insert into value_state (code, datasets) values ('väldi', '{}');
insert into value_state (code, datasets) values ('endine', '{}');
insert into word_rel_type (code, datasets) values ('posit', '{}');
insert into word_rel_type (code, datasets) values ('deriv_base', '{}');
insert into word_rel_type (code, datasets) values ('komp', '{}');
insert into word_rel_type (code, datasets) values ('superl', '{}');
insert into word_rel_type (code, datasets) values ('deriv', '{}');
insert into word_rel_type (code, datasets) values ('SERIES', '{}');
insert into word_rel_type (code, datasets) values ('VARIANTS', '{}');
insert into word_type (code, datasets) values ('k', '{}');
insert into word_type (code, datasets) values ('l', '{}');
insert into word_type (code, datasets) values ('p', '{}');
insert into word_type (code, datasets) values ('z', '{}');
insert into word_type (code, datasets) values ('mvv', '{}');
insert into word_type (code, datasets) values ('yv', '{}');
insert into word_type (code, datasets) values ('vv', '{}');
insert into word_type (code, datasets) values ('av', '{}');
insert into word_type (code, datasets) values ('tv', '{}');
insert into word_type (code, datasets) values ('vlj', '{}');
insert into word_type (code, datasets) values ('ys', '{}');
insert into word_type (code, datasets) values ('rs', '{}');
insert into word_type (code, datasets) values ('f', '{}');
insert into word_type (code, datasets) values ('mf', '{}');
insert into word_type (code, datasets) values ('g', '{}');
insert into word_type (code, datasets) values ('lz', '{}');
insert into word_type (code, datasets) values ('n', '{}');
insert into word_type (code, datasets) values ('pf', '{}');
insert into word_type (code, datasets) values ('s', '{}');
insert into word_type (code, datasets) values ('km', '{}');
insert into word_type (code, datasets) values ('th', '{}');
insert into word_type (code, datasets) values ('valem', '{}');
insert into word_type (code, datasets) values ('termin', '{}');
insert into word_type (code, datasets) values ('tõlkeprobleem', '{}');
insert into word_type (code, datasets) values ('ametinimetus', '{}');
insert into word_type (code, datasets) values ('organisatsiooni, asutuse nimi', '{}');
insert into word_type (code, datasets) values ('õigusakti pealkiri', '{}');
insert into word_type (code, datasets) values ('dokumendi pealkiri', '{}');

insert into aspect_type_label (code, value, lang, type) values ('sov', 'совершенный', 'est', 'descrip');
insert into aspect_type_label (code, value, lang, type) values ('nesov', 'не совершенный', 'est', 'descrip');
insert into aspect_type_label (code, value, lang, type) values ('sov/nesov', 'совершенный/не совершенный', 'est', 'descrip');
insert into deriv_label (code, value, lang, type) values ('adv', 'adverb (-lt)', 'est', 'descrip');
insert into deriv_label (code, value, lang, type) values ('dem', 'KE/KENE', 'est', 'ekimorfo');
insert into deriv_label (code, value, lang, type) values ('dem', 'diminutive', 'eng', 'descrip');
insert into deriv_label (code, value, lang, type) values ('dem', 'deminutiiv, vähendussõna', 'est', 'descrip');
insert into deriv_label (code, value, lang, type) values ('dem', 'deminutiiv, vähendussõna (-ke, -kene)', 'est', 'descrip2');
insert into deriv_label (code, value, lang, type) values ('dem', 'dem', 'lat', 'abbrev');
insert into deriv_label (code, value, lang, type) values ('komp', 'M', 'est', 'ekimorfo');
insert into deriv_label (code, value, lang, type) values ('komp', 'comparative (degree)', 'eng', 'descrip');
insert into deriv_label (code, value, lang, type) values ('komp', 'komparatiiv, keskvõrre', 'est', 'descrip');
insert into deriv_label (code, value, lang, type) values ('komp', 'komparatiiv, keskvõrre (-m)', 'est', 'descrip2');
insert into deriv_label (code, value, lang, type) values ('komp', 'keskv', 'est', 'abbrev');
insert into deriv_label (code, value, lang, type) values ('komp', 'komp', 'lat', 'abbrev');
insert into deriv_label (code, value, lang, type) values ('superl', 'IM', 'est', 'ekimorfo');
insert into deriv_label (code, value, lang, type) values ('superl', 'superlative (degree)', 'eng', 'descrip');
insert into deriv_label (code, value, lang, type) values ('superl', 'superlatiiv, ülivõrre', 'est', 'descrip');
insert into deriv_label (code, value, lang, type) values ('superl', 'superlatiiv, ülivõrre (-im)', 'est', 'descrip2');
insert into deriv_label (code, value, lang, type) values ('superl', 'üliv', 'est', 'abbrev');
insert into deriv_label (code, value, lang, type) values ('superl', 'superl', 'lat', 'abbrev');
insert into deriv_label (code, value, lang, type) values ('tgn', 'JA', 'est', 'ekimorfo');
insert into deriv_label (code, value, lang, type) values ('tgn', 'ja-derivative = actor', 'eng', 'descrip');
insert into deriv_label (code, value, lang, type) values ('tgn', 'tegijanimi', 'est', 'descrip');
insert into deriv_label (code, value, lang, type) values ('tgn', 'tegijanimi (-ja)', 'est', 'descrip2');
insert into deriv_label (code, value, lang, type) values ('tgn', 'tgn', 'est', 'abbrev');
insert into deriv_label (code, value, lang, type) values ('tn', 'MINE', 'est', 'ekimorfo');
insert into deriv_label (code, value, lang, type) values ('tn', 'mine-derivative = act, process', 'eng', 'descrip');
insert into deriv_label (code, value, lang, type) values ('tn', 'teonimi', 'est', 'descrip');
insert into deriv_label (code, value, lang, type) values ('tn', 'teonimi (-mine)', 'est', 'descrip2');
insert into deriv_label (code, value, lang, type) values ('tn', 'tn', 'est', 'abbrev');
insert into deriv_label (code, value, lang, type) values ('as', 'US', 'est', 'ekimorfo');
insert into deriv_label (code, value, lang, type) values ('posit', '_', 'est', 'ekimorfo');
insert into deriv_label (code, value, lang, type) values ('as', 'as', 'lat', 'abbrev');
insert into deriv_label (code, value, lang, type) values ('posit', 'algvõrre', 'est', 'descrip');
insert into deriv_label (code, value, lang, type) values ('as', 'abstraktne substantiiv', 'est', 'descrip');
insert into deriv_label (code, value, lang, type) values ('posit', 'positiiv, algvõrre', 'est', 'descrip2');
insert into deriv_label (code, value, lang, type) values ('as', 'abstract substantive', 'eng', 'descrip');
insert into deriv_label (code, value, lang, type) values ('posit', 'positive degree', 'eng', 'descrip');
insert into deriv_label (code, value, lang, type) values ('ssv', 'seisundivorm', 'est', 'descrip');
insert into deriv_label (code, value, lang, type) values ('komp', 'keskvõrre', 'est', 'wordweb');
insert into deriv_label (code, value, lang, type) values ('tgn', 'tegijanimi', 'est', 'wordweb');
insert into deriv_label (code, value, lang, type) values ('tn', 'teonimi', 'est', 'wordweb');
insert into deriv_label (code, value, lang, type) values ('posit', 'algvõrre', 'est', 'wordweb');
insert into deriv_label (code, value, lang, type) values ('adv', 'määrsõna', 'est', 'wordweb');
insert into deriv_label (code, value, lang, type) values ('superl', 'ülivõrre', 'est', 'wordweb');
insert into deriv_label (code, value, lang, type) values ('dem', 'vähendussõna', 'est', 'wordweb');
insert into deriv_label (code, value, lang, type) values ('ssv', 'seisundivorm', 'est', 'wordweb');
insert into deriv_label (code, value, lang, type) values ('as', 'nimisõna', 'est', 'wordweb');
insert into display_morph_label (code, value, lang, type) values ('keskv', 'komparatiiv, keskvõrre', 'est', 'descrip');
insert into display_morph_label (code, value, lang, type) values ('keskv', 'comparative (degree)', 'eng', 'descrip');
insert into display_morph_label (code, value, lang, type) values ('üliv', 'superlatiiv, ülivõrre', 'est', 'descrip');
insert into display_morph_label (code, value, lang, type) values ('üliv', 'superlative (degree)', 'eng', 'descrip');
insert into display_morph_label (code, value, lang, type) values ('ips', 'impersonaal, umbisikuline tegumood', 'est', 'descrip');
insert into display_morph_label (code, value, lang, type) values ('ips', 'impersonal', 'eng', 'descrip');
insert into display_morph_label (code, value, lang, type) values ('ipf', 'lihtminevik', 'est', 'descrip');
insert into display_morph_label (code, value, lang, type) values ('pts', 'partitsiip, kesksõna', 'est', 'descrip');
insert into display_morph_label (code, value, lang, type) values ('pts', 'participle', 'eng', 'descrip');
insert into display_morph_label (code, value, lang, type) values ('pl', 'pluural, mitmus', 'est', 'descrip');
insert into display_morph_label (code, value, lang, type) values ('pl', 'plural', 'eng', 'descrip');
insert into display_morph_label (code, value, lang, type) values ('sg', 'singular, ainsus', 'est', 'descrip');
insert into display_morph_label (code, value, lang, type) values ('sg', 'singular', 'eng', 'descrip');
insert into display_morph_label (code, value, lang, type) values ('Ipf', 'lihtminevik', 'est', 'wordweb');
insert into display_morph_label (code, value, lang, type) values ('Sg', 'ainsus', 'est', 'wordweb');
insert into display_morph_label (code, value, lang, type) values ('Pl', 'mitmus', 'est', 'wordweb');
insert into display_morph_label (code, value, lang, type) values ('Ips', 'umbisikuline tegumood', 'est', 'wordweb');
insert into display_morph_label (code, value, lang, type) values ('Pts', 'kesksõna', 'est', 'wordweb');
insert into form_rel_type_label (code, value, lang, type) values ('mvt', 'viitemärksõna', 'est', 'full');
insert into gender_label (code, value, lang, type) values ('f', 'feminine', 'eng', 'descrip');
insert into gender_label (code, value, lang, type) values ('f', 'naissugu', 'est', 'descrip');
insert into gender_label (code, value, lang, type) values ('n', 'neuter', 'eng', 'descrip');
insert into gender_label (code, value, lang, type) values ('n', 'kesksugu', 'est', 'descrip');
insert into gender_label (code, value, lang, type) values ('o', 'other', 'eng', 'descrip');
insert into gender_label (code, value, lang, type) values ('o', 'muu', 'est', 'descrip');
insert into gender_label (code, value, lang, type) values ('m', 'masculine', 'eng', 'descrip');
insert into gender_label (code, value, lang, type) values ('m', 'meessugu', 'est', 'descrip');
insert into gender_label (code, value, lang, type) values ('n', 'kesksugu', 'est', 'wordweb');
insert into gender_label (code, value, lang, type) values ('m', 'meessugu', 'est', 'wordweb');
insert into gender_label (code, value, lang, type) values ('o', 'muu', 'est', 'wordweb');
insert into gender_label (code, value, lang, type) values ('f', 'naissugu', 'est', 'wordweb');
insert into government_type_label (code, value, lang, type) values ('obj', 'objektirektsioon', 'est', 'full');
insert into government_type_label (code, value, lang, type) values ('kn', 'käänderektsioon', 'est', 'full');
insert into government_type_label (code, value, lang, type) values ('ks', 'kaassõnarektsioon', 'est', 'full');
insert into government_type_label (code, value, lang, type) values ('yld', 'üldrektsioon', 'est', 'full');
insert into government_type_label (code, value, lang, type) values ('inf', 'infinitiivirektsioon', 'est', 'full');
insert into government_type_label (code, value, lang, type) values ('kla', 'lausungirektsioon', 'est', 'full');
insert into government_type_label (code, value, lang, type) values ('subj', 'subjektirektsioon', 'est', 'full');
insert into lex_rel_type_label (code, value, lang, type) values ('comp', 'liitsõna', 'est', 'full');
insert into lex_rel_type_label (code, value, lang, type) values ('head', 'põhisõna', 'est', 'full');
insert into lex_rel_type_label (code, value, lang, type) values ('vor', 'vormel', 'est', 'full');
insert into lex_rel_type_label (code, value, lang, type) values ('yvr', 'üksikvorm', 'est', 'full');
insert into lex_rel_type_label (code, value, lang, type) values ('pyh', 'ühend', 'est', 'full');
insert into lex_rel_type_label (code, value, lang, type) values ('yhvt', 'ühendviide', 'est', 'full');
insert into lex_rel_type_label (code, value, lang, type) values ('tvt:vrd', 'tähendusviide, võrdle', 'est', 'full');
insert into lex_rel_type_label (code, value, lang, type) values ('tvt:vt ka', 'tähendusviide, vaata ka', 'est', 'full');
insert into lex_rel_type_label (code, value, lang, type) values ('yvt:vrd', 'ühisviide, võrdle tähendust', 'est', 'full');
insert into lex_rel_type_label (code, value, lang, type) values ('yvt:vt ka', 'ühisviide, vaata ka', 'est', 'full');
insert into lex_rel_type_label (code, value, lang, type) values ('yvt:NB', 'ühisviide, ära aja segi', 'est', 'full');
insert into lex_rel_type_label (code, value, lang, type) values ('lyh', 'lühend', 'est', 'full');
insert into lex_rel_type_label (code, value, lang, type) values ('mm', 'allmärksõna', 'est', 'full');
insert into lex_rel_type_label (code, value, lang, type) values ('yvt:NB', 'ära aja segi', 'est', 'wordweb');
insert into lex_rel_type_label (code, value, lang, type) values ('yvt:vt ka', 'vaata ka', 'est', 'wordweb');
insert into lex_rel_type_label (code, value, lang, type) values ('yvt:vrd', 'võrdle', 'est', 'wordweb');
insert into lex_rel_type_label (code, value, lang, type) values ('comp', 'liitsõna', 'est', 'wordweb');
insert into lex_rel_type_label (code, value, lang, type) values ('lyh', 'lühend', 'est', 'wordweb');
insert into lex_rel_type_label (code, value, lang, type) values ('head', 'põhisõna', 'est', 'wordweb');
insert into lex_rel_type_label (code, value, lang, type) values ('pyh', 'ühend', 'est', 'wordweb');
insert into lex_rel_type_label (code, value, lang, type) values ('yvr', 'üksikvorm', 'est', 'wordweb');
insert into lex_rel_type_label (code, value, lang, type) values ('tvt:vt ka', 'vaata ka', 'est', 'wordweb');
insert into lex_rel_type_label (code, value, lang, type) values ('yhvt', 'vaata ka', 'est', 'wordweb');
insert into lex_rel_type_label (code, value, lang, type) values ('vor', 'suhtlus, vestlus', 'est', 'wordweb');
insert into lex_rel_type_label (code, value, lang, type) values ('tvt:vrd', 'võrdle', 'est', 'wordweb');
insert into meaning_rel_type_label (code, value, lang, type) values ('ant', 'antonüüm', 'est', 'descrip');
insert into meaning_rel_type_label (code, value, lang, type) values ('cohyponym', 'kaashüponüüm', 'est', 'descrip');
insert into meaning_rel_type_label (code, value, lang, type) values ('cohyponym', 'kaashüponüüm', 'est', 'wordweb');
insert into meaning_rel_type_label (code, value, lang, type) values ('ant', 'vastand', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('ID', 'muutumatu', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('SgN', 'ainsuse nimetav', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('SgN', 'SgN', 'eng', 'descrip2');
insert into morph_label (code, value, lang, type) values ('SgG', 'ainsuse omastav', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('SgP', 'ainsuse osastav', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('SgAdt', 'ainsuse suunduv', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('SgIll', 'ainsuse sisseütlev', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('SgIn', 'ainsuse seesütlev', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('SgEl', 'ainsuse seestütlev', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('SgAll', 'ainsuse alaleütlev', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('SgAd', 'ainsuse alalütlev', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('SgAbl', 'ainsuse alaltütlev', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('SgTr', 'ainsuse saav', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('SgTer', 'ainsuse rajav', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('SgEs', 'ainsuse olev', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('SgAb', 'ainsuse ilmaütlev', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('SgKom', 'ainsuse kaasaütlev', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('PlN', 'mitmuse nimetav', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('PlG', 'mitmuse omastav', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('PlP', 'mitmuse osastav', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('PlAdt', 'mitmuse aditiiv', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('PlIll', 'mitmuse sisseütlev', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('PlIn', 'mitmuse seesütlev', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('PlEl', 'mitmuse seestütlev', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('PlAll', 'mitmuse alaleütlev', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('PlAd', 'mitmuse alalütlev', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('PlAbl', 'mitmuse alaltütlev', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('PlTr', 'mitmuse saav', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('PlTer', 'mitmuse rajav', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('PlEs', 'mitmuse olev', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('PlAb', 'mitmuse ilmaütlev', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('PlKom', 'mitmuse kaasaütlev', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('Sup', 'MA = ma-tegevusnimi', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('Inf', 'DA = da-tegevusnimi', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('IndPrSg3', 'B = kindla kv oleviku ainsuse 3. p', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('IndPrPl1', 'ME = kindla kv oleviku mitmuse 1. p', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('PtsPtIps', 'TUD = tud-kesksõna', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('IndIpfSg3', 'S = lihtmineviku ainsuse 3. p', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('PtsPtPs', 'NUD = nud-kesksõna', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('ImpPrPl2', 'GE = käskiva kv mitmuse 2. p', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('IndPrIps', 'TAKSE = umbisikulise tm olevik', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('PtsPrIps', 'TAV = tav-kesksõna', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('IndPrPsN', 'POLE = kindla kv oleviku eitus', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('IndIpfPsN', 'POLNUD = kindla kv mineviku eitus', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('Neg', 'EI = eitus', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('ImpPrSg2N', 'ÄRA = käskiva kv oleviku sg 2.p. eitus', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('ImpPrPl2N', 'ÄRGE = käskiva kv oleviku pl 2.p. eitus', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('ImpPrPl1N', 'ÄRGEM = käskiva kv oleviku pl 1.p. eitus', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('ImpPrN', 'ÄRGU = käskiva kv oleviku isikuline eitus', 'est', 'descrip2');
insert into morph_label (code, value, lang, type) values ('ID', 'indekl', 'lat', 'abbrev');
insert into morph_label (code, value, lang, type) values ('SgN', 'nom', 'lat', 'abbrev');
insert into morph_label (code, value, lang, type) values ('SgG', 'sg gen, gen', 'lat', 'abbrev');
insert into morph_label (code, value, lang, type) values ('SgP', 'part', 'lat', 'abbrev');
insert into morph_label (code, value, lang, type) values ('SgIll', 'illat', 'lat', 'abbrev');
insert into morph_label (code, value, lang, type) values ('SgIn', 'iness', 'lat', 'abbrev');
insert into morph_label (code, value, lang, type) values ('SgEl', 'adess', 'lat', 'abbrev');
insert into morph_label (code, value, lang, type) values ('PlN', 'pl nom', 'lat', 'abbrev');
insert into morph_label (code, value, lang, type) values ('PlG', 'pl gen', 'lat', 'abbrev');
insert into morph_label (code, value, lang, type) values ('PlP', 'pl part', 'lat', 'abbrev');
insert into morph_label (code, value, lang, type) values ('PlIll', 'pl illat', 'lat', 'abbrev');
insert into morph_label (code, value, lang, type) values ('PlIn', 'pl iness', 'lat', 'abbrev');
insert into morph_label (code, value, lang, type) values ('PlEl', 'pl elat', 'lat', 'abbrev');
insert into morph_label (code, value, lang, type) values ('PlTer', 'pl term', 'lat', 'abbrev');
insert into morph_label (code, value, lang, type) values ('SgN', 'SgN', 'eng', 'abbrev');
insert into morph_label (code, value, lang, type) values ('SgG', 'om', 'est', 'abbrev');
insert into morph_label (code, value, lang, type) values ('SgP', 'os', 'est', 'abbrev');
insert into morph_label (code, value, lang, type) values ('ID', '--------', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('??', '------xx', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('SgN', '------0N', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('SgG', '------0G', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('SgP', '------0P', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('SgAdt', '------0D', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('SgIll', '------01', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('SgIn', '------02', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('SgEl', '------03', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('SgAll', '------04', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('SgAd', '------05', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('SgAbl', '------06', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('SgTr', '------0T', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('SgTer', '------0R', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('SgEs', '------0E', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('SgAb', '------0A', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('SgKom', '------0K', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('PlN', '------1N', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('PlG', '------1G', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('PlP', '------1P', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('PlIll', '------11', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('PlIn', '------12', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('PlEl', '------13', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('PlAll', '------14', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('PlAd', '------15', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('PlAbl', '------16', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('PlTr', '------1T', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('PlTer', '------1R', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('PlEs', '------1E', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('PlAb', '------1A', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('PlKom', '------1K', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('Rpl', '------1-', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('Nlyhi', '------RC', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('Nvahe', '------HC', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('Sup', '30------', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('SupAb', '30-----A', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('SupIn', '30-----2', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('SupEl', '30-----3', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('SupTr', '30-----T', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('SupIps', '31------', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('Inf', '1-------', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('Ger', '2-------', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('PtsPrPs', '400---0N', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('PtsPrIps', '410---0N', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('PtsPtPs', '401--0--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('PtsPtIps', '411--0--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('IndPrSg1', '-00011--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('IndPrSg2', '-00021--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('IndPrSg3', '-00031--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('IndPrPl1', '-00041--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('IndPrPl2', '-00051--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('IndPrPl3', '-00061--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('IndPrPs_', '-00000--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('IndPrIps', '-100-1--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('IndPrIps_', '-100-0--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('IndIpfSg1', '-02011--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('IndIpfSg2', '-02021--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('IndIpfSg3', '-02031--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('IndIpfPl1', '-02041--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('IndIpfPl2', '-02051--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('IndIpfPl3', '-02061--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('IndIpfIps', '-120-1--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('KndPrSg1', '-00211--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('KndPrSg2', '-00221--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('KndPrPs', '-00200--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('KndPrPl1', '-00241--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('KndPrPl2', '-00251--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('KndPrPl3', '-00261--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('KndPrIps', '-102-0--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('KndPtSg1', '-01211--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('KndPtSg2', '-01221--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('KndPtPs', '-01200--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('KndPtPl1', '-01241--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('KndPtPl2', '-01251--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('KndPtPl3', '-01261--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('KndPtIps', '-112-0--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('KvtPrPs', '-00100--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('KvtPrIps', '-101-0--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('KvtPtPs', '-01100--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('KvtPtIps', '-111-0--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('ImpPrSg2', '-00320--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('ImpPrPl1', '-00340--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('ImpPrPl2', '-00350--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('ImpPrPs', '-00300--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('ImpPrIps', '-103-0--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('Vlyhi', 'RC------', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('Vvahe', 'RC------', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('Neg', '-----2--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('ImpPrSg2N', '-00322--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('ImpPrPl1N', '-00342--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('ImpPrPl2N', '-00352--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('ImpPrN', '--0302--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('IndPrPsN', '-00002--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('IndPrIpsN', '-100-2--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('IndIpfPsN', '-02002--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('IndIpfIpsN', '-120-2--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('KvtPrPsN', '-00102--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('KvtPtPsN', '-01102--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('KndPrPsN', '-00202--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('KndPtPsN', '-01202--', 'est', 'ekimorfo');
insert into morph_label (code, value, lang, type) values ('ID', 'muutumatu sõna (indekl)', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('??', 'määramatu vorm', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('SgN', 'ainsuse nimetav', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('SgG', 'ainsuse omastav', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('SgP', 'ainsuse osastav', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('SgAdt', 'ainsuse suunduv e lühike sisseütlev', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('SgIll', 'ainsuse sisseütlev', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('SgIn', 'ainsuse seesütlev', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('SgEl', 'ainsuse seestütlev', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('SgAll', 'ainsuse alaleütlev', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('SgAd', 'ainsuse alalütlev', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('SgAbl', 'ainsuse alaltütlev', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('SgTr', 'ainsuse saav', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('SgTer', 'ainsuse rajav', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('SgEs', 'ainsuse olev', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('SgAb', 'ainsuse ilmaütlev', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('SgKom', 'ainsuse kaasaütlev', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('PlN', 'mitmuse nimetav', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('PlG', 'mitmuse omastav', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('PlP', 'mitmuse osastav', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('PlIll', 'mitmuse sisseütlev', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('PlIn', 'mitmuse seesütlev', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('PlEl', 'mitmuse seestütlev', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('PlAll', 'mitmuse alaleütlev', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('PlAd', 'mitmuse alalütlev', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('PlAbl', 'mitmuse alaltütlev', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('PlTr', 'mitmuse saav', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('PlTer', 'mitmuse rajav', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('PlEs', 'mitmuse olev', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('PlAb', 'mitmuse ilmaütlev', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('PlKom', 'mitmuse kaasaütlev', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('Sup', 'ma-infinitiiv e ma-tegevusnimi', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('SupAb', 'mata-vorm', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('SupIn', 'mas-vorm', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('SupEl', 'mast-vorm', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('SupTr', 'maks-vorm', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('SupIps', 'ma-tegevusnime umbisikuline tegumood', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('Inf', 'da-infinitiiv e da-tegevusnimi', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('Ger', 'des-vorm', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('PtsPrPs', 'oleviku isikuline kesksõna e v-kesksõna', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('PtsPrIps', 'oleviku umbisikuline kesksõna e tav-kesksõna', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('PtsPtPs', 'mineviku isikuline kesksõna e nud-kesksõna', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('PtsPtIps', 'mineviku umbisikuline kesksõna e tud-kesksõna', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('IndPrSg1', 'kindla kõneviisi oleviku ainsuse 1.pööre', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('IndPrSg2', 'kindla kõneviisi oleviku ainsuse 2.p.', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('IndPrSg3', 'kindla kõneviisi oleviku ainsuse 3.p.', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('IndPrPl1', 'kindla kõneviisi oleviku mitmuse 1.p.', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('IndPrPl2', 'kindla kõneviisi oleviku mitmuse 2.p.', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('IndPrPl3', 'kindla kõneviisi oleviku mitmuse 3.p.', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('IndPrPs_', 'kindla kõneviisi oleviku isikuline tegumood (eitusega)', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('IndPrIps', 'kindla kõneviisi oleviku umbisikuline tegumood', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('IndPrIps_', 'kindla kõneviisi oleviku umbisikuline tegumood (eitusega)', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('IndIpfSg1', 'kindla kõneviisi lihtmineviku ainsuse 1.p.', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('IndIpfSg2', 'kindla kõneviisi lihtmineviku ainsuse 2.p.', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('IndIpfSg3', 'kindla kõneviisi lihtmineviku ainsuse 3.p.', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('IndIpfPl1', 'kindla kõneviisi lihtmineviku mitmuse 1.p.', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('IndIpfPl2', 'kindla kõneviisi lihtmineviku mitmuse 2.p.', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('IndIpfPl3', 'kindla kõneviisi lihtmineviku mitmuse 3.p.', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('IndIpfIps', 'kindla kõneviisi lihtmineviku umbisikuline tegumood', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('KndPrSg1', 'tingiva kõneviisi oleviku ainsuse 1.p.', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('KndPrSg2', 'tingiva kõneviisi oleviku ainsuse 2.p.', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('KndPrPs', 'tingiva kõneviisi oleviku isikuline tegumood', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('KndPrPl1', 'tingiva kõneviisi oleviku mitmuse 1.p.', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('KndPrPl2', 'tingiva kõneviisi oleviku mitmuse 2.p.', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('KndPrPl3', 'tingiva kõneviisi oleviku mitmuse 3.p.', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('KndPrIps', 'tingiva kõneviisi oleviku umbisikuline tegumood', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('KndPtSg1', 'tingiva kõneviisi mineviku ainsuse 1.p.', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('KndPtSg2', 'tingiva kõneviisi mineviku ainsuse 2.p.', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('KndPtPs', 'tingiva kõneviisi mineviku isikuline tegumood', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('KndPtPl1', 'tingiva kõneviisi mineviku mitmuse 1.p.', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('KndPtPl2', 'tingiva kõneviisi mineviku mitmuse 2.p.', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('KndPtPl3', 'tingiva kõneviisi mineviku mitmuse 3.p.', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('KndPtIps', 'tingiva kõneviisi mineviku umbisikuline tegumood', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('KvtPrPs', 'kaudse kõneviisi oleviku isikuline tegumood', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('KvtPrIps', 'kaudse kõneviisi oleviku umbisikuline tegumood', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('KvtPtPs', 'kaudse kõneviisi mineviku isikuline tegumood', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('KvtPtIps', 'kaudse kõneviisi mineviku umbisikuline tegumood', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('ImpPrSg2', 'käskiva kõneviisi oleviku ainsuse 2.p.', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('ImpPrPl1', 'käskiva kõneviisi oleviku mitmuse 1.p.', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('ImpPrPl2', 'käskiva kõneviisi oleviku mitmuse 2.p.', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('ImpPrPs', 'käskiva kõneviisi oleviku isikuline tegumood', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('ImpPrIps', 'käskiva kõneviisi oleviku umbisikuline tegumood', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('Neg', 'eitus (ei)', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('ImpPrSg2N', 'käskiva kõneviisi oleviku ainsuse 2.p. eitus (ära)', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('ImpPrPl1N', 'käskiva kõneviisi oleviku mitmuse 1.p. eitus (ärgem)', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('ImpPrPl2N', 'käskiva kõneviisi oleviku mitmuse 2.p. eitus (ärge)', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('ImpPrN', 'käskiva kõneviisi oleviku isikulise tegumoe eitus (ärgu)', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('IndPrPsN', 'pole', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('IndPrIpsN', 'polda', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('IndIpfPsN', 'polnud', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('IndIpfIpsN', 'poldud', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('KvtPrPsN', 'polevat', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('KvtPtPsN', 'polnuvat', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('KndPrPsN', 'poleks', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('KndPtPsN', 'polnuks', 'est', 'descrip');
insert into morph_label (code, value, lang, type) values ('SgAll', 'ainsuse alaleütlev', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('SgAbl', 'ainsuse alaltütlev', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('SgAd', 'ainsuse alalütlev', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('SgAb', 'ainsuse ilmaütlev', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('SgKom', 'ainsuse kaasaütlev', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('SgAdt', 'ainsuse lühike sisseütlev', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('SgN', 'ainsuse nimetav', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('SgEs', 'ainsuse olev', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('SgG', 'ainsuse omastav', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('SgP', 'ainsuse osastav', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('SgTer', 'ainsuse rajav', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('SgTr', 'ainsuse saav', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('SgEl', 'ainsuse seestütlev', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('SgIn', 'ainsuse seesütlev', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('SgIll', 'ainsuse sisseütlev', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('Inf', 'da-tegevusnimi', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('Neg', 'eitus (ei)', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('ImpPrSg2', 'käskiva kõneviisi oleviku ainsuse 2.p.', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('ImpPrSg2N', 'käskiva kõneviisi oleviku ainsuse 2.p. eitus (ära)', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('ImpPrPs', 'käskiva kõneviisi oleviku isikuline tegumood', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('ImpPrN', 'käskiva kõneviisi oleviku isikulise tegumoe eitus (ärgu)', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('ImpPrPl1', 'käskiva kõneviisi oleviku mitmuse 1.p.', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('ImpPrPl1N', 'käskiva kõneviisi oleviku mitmuse 1.p. eitus (ärgem)', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('ImpPrPl2', 'käskiva kõneviisi oleviku mitmuse 2.p.', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('ImpPrPl2N', 'käskiva kõneviisi oleviku mitmuse 2.p. eitus (ärge)', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('ImpPrIps', 'käskiva kõneviisi oleviku umbisikuline tegumood', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('KvtPtPs', 'kaudse kõneviisi mineviku isikuline tegumood', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('KvtPtIps', 'kaudse kõneviisi mineviku umbisikuline tegumood', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('KvtPrPs', 'kaudse kõneviisi oleviku isikuline tegumood', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('KvtPrIps', 'kaudse kõneviisi oleviku umbisikuline tegumood', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('IndIpfSg1', 'kindla kõneviisi lihtmineviku ainsuse 1.p.', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('IndIpfSg2', 'kindla kõneviisi lihtmineviku ainsuse 2.p.', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('IndIpfSg3', 'kindla kõneviisi lihtmineviku ainsuse 3.p.', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('IndIpfPl1', 'kindla kõneviisi lihtmineviku mitmuse 1.p.', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('IndIpfPl2', 'kindla kõneviisi lihtmineviku mitmuse 2.p.', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('IndIpfPl3', 'kindla kõneviisi lihtmineviku mitmuse 3.p.', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('IndIpfIps', 'kindla kõneviisi lihtmineviku umbisikuline tegumood', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('IndPrSg1', 'kindla kõneviisi oleviku ainsuse 1.pööre', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('IndPrSg2', 'kindla kõneviisi oleviku ainsuse 2.p.', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('IndPrSg3', 'kindla kõneviisi oleviku ainsuse 3.p.', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('IndPrPs_', 'kindla kõneviisi oleviku isikuline tegumood (eitusega)', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('IndPrPl1', 'kindla kõneviisi oleviku mitmuse 1.p.', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('IndPrPl2', 'kindla kõneviisi oleviku mitmuse 2.p.', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('IndPrPl3', 'kindla kõneviisi oleviku mitmuse 3.p.', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('IndPrIps', 'kindla kõneviisi oleviku umbisikuline tegumood', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('IndPrIps_', 'kindla kõneviisi oleviku umbisikuline tegumood (eitusega)', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('??', 'määramatu vorm', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('SupTr', 'maks-vorm', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('SupEl', 'mast-vorm', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('SupIn', 'mas-vorm', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('SupAb', 'mata-vorm', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('SupIps', 'ma-tegevusnime umbisikuline tegumood', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('Sup', 'ma-tegevusnimi', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('PlAll', 'mitmuse alaleütlev', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('PlAbl', 'mitmuse alaltütlev', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('PlAd', 'mitmuse alalütlev', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('PlAb', 'mitmuse ilmaütlev', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('PlKom', 'mitmuse kaasaütlev', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('PlAdt', 'mitmuse lühike sisseütlev', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('PlN', 'mitmuse nimetav', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('PlEs', 'mitmuse olev', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('PlG', 'mitmuse omastav', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('PlP', 'mitmuse osastav', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('PlTer', 'mitmuse rajav', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('PlTr', 'mitmuse saav', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('PlEl', 'mitmuse seestütlev', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('PlIn', 'mitmuse seesütlev', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('PlIll', 'mitmuse sisseütlev', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('ID', 'muutumatu', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('PtsPtPs', 'nud-kesksõna', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('IndPrIpsN', 'polda', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('IndIpfIpsN', 'poldud', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('IndPrPsN', 'pole', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('KndPrPsN', 'poleks', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('KvtPrPsN', 'polevat', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('IndIpfPsN', 'polnud', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('KndPtPsN', 'polnuks', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('KvtPtPsN', 'polnuvat', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('PtsPrIps', 'tav-kesksõna', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('KndPtSg1', 'tingiva kõneviisi mineviku ainsuse 1.p.', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('KndPtSg2', 'tingiva kõneviisi mineviku ainsuse 2.p.', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('KndPtPs', 'tingiva kõneviisi mineviku isikuline tegumood', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('KndPtPl1', 'tingiva kõneviisi mineviku mitmuse 1.p.', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('KndPtPl2', 'tingiva kõneviisi mineviku mitmuse 2.p.', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('KndPtPl3', 'tingiva kõneviisi mineviku mitmuse 3.p.', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('KndPtIps', 'tingiva kõneviisi mineviku umbisikuline tegumood', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('KndPrSg1', 'tingiva kõneviisi oleviku ainsuse 1.p.', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('KndPrSg2', 'tingiva kõneviisi oleviku ainsuse 2.p.', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('KndPrPs', 'tingiva kõneviisi oleviku isikuline tegumood', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('KndPrPl1', 'tingiva kõneviisi oleviku mitmuse 1.p.', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('KndPrPl2', 'tingiva kõneviisi oleviku mitmuse 2.p.', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('KndPrPl3', 'tingiva kõneviisi oleviku mitmuse 3.p.', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('KndPrIps', 'tingiva kõneviisi oleviku umbisikuline tegumood', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('PtsPtIps', 'tud-kesksõna', 'est', 'wordweb');
insert into morph_label (code, value, lang, type) values ('PtsPrPs', 'v-kesksõna', 'est', 'wordweb');
insert into pos_label (code, value, lang, type) values ('adj', 'A', 'est', 'capital');
insert into pos_label (code, value, lang, type) values ('adj', 'adjektiiv, omadussõna', 'est', 'descrip');
insert into pos_label (code, value, lang, type) values ('adj', 'adjective', 'eng', 'descrip');
insert into pos_label (code, value, lang, type) values ('adv', 'D', 'est', 'capital');
insert into pos_label (code, value, lang, type) values ('adv', 'adverb, määrsõna', 'est', 'descrip');
insert into pos_label (code, value, lang, type) values ('adv', 'adverb', 'eng', 'descrip');
insert into pos_label (code, value, lang, type) values ('adjg', 'G', 'est', 'capital');
insert into pos_label (code, value, lang, type) values ('adjg', 'genitiivatribuut, omastavaline täiend', 'est', 'descrip');
insert into pos_label (code, value, lang, type) values ('adjg', 'attribute in genitive', 'eng', 'descrip');
insert into pos_label (code, value, lang, type) values ('prop', 'H', 'est', 'capital');
insert into pos_label (code, value, lang, type) values ('prop', 'prooprium, pärisnimi', 'est', 'descrip');
insert into pos_label (code, value, lang, type) values ('prop', 'proper noun', 'eng', 'descrip');
insert into pos_label (code, value, lang, type) values ('interj', 'I', 'est', 'capital');
insert into pos_label (code, value, lang, type) values ('interj', 'interjektsioon, hüüdsõna', 'est', 'descrip');
insert into pos_label (code, value, lang, type) values ('interj', 'interjection', 'eng', 'descrip');
insert into pos_label (code, value, lang, type) values ('konj', 'J', 'est', 'capital');
insert into pos_label (code, value, lang, type) values ('konj', 'konjunktsioon, sidesõna', 'est', 'descrip');
insert into pos_label (code, value, lang, type) values ('konj', 'conjunction', 'eng', 'descrip');
insert into pos_label (code, value, lang, type) values ('adp', 'K', 'est', 'capital');
insert into pos_label (code, value, lang, type) values ('adp', 'adpositsioon, kaassõna', 'est', 'descrip');
insert into pos_label (code, value, lang, type) values ('adp', 'postposition, preposition', 'eng', 'descrip');
insert into pos_label (code, value, lang, type) values ('num', 'N', 'est', 'capital');
insert into pos_label (code, value, lang, type) values ('num', 'numeraal, arvsõna', 'est', 'descrip');
insert into pos_label (code, value, lang, type) values ('num', 'cardinal, numeral', 'eng', 'descrip');
insert into pos_label (code, value, lang, type) values ('ord', 'O', 'est', 'capital');
insert into pos_label (code, value, lang, type) values ('ord', 'ordinaal, järgarvsõna', 'est', 'descrip');
insert into pos_label (code, value, lang, type) values ('ord', 'ordinal', 'eng', 'descrip');
insert into pos_label (code, value, lang, type) values ('pron', 'P', 'est', 'capital');
insert into pos_label (code, value, lang, type) values ('pron', 'pronoomen, asesõna', 'est', 'descrip');
insert into pos_label (code, value, lang, type) values ('pron', 'pronoun', 'eng', 'descrip');
insert into pos_label (code, value, lang, type) values ('s', 'S', 'est', 'capital');
insert into pos_label (code, value, lang, type) values ('s', 'substantiiv, nimisõna', 'est', 'descrip');
insert into pos_label (code, value, lang, type) values ('s', 'substantive', 'eng', 'descrip');
insert into pos_label (code, value, lang, type) values ('v', 'V', 'est', 'capital');
insert into pos_label (code, value, lang, type) values ('v', 'verb, tegusõna', 'est', 'descrip');
insert into pos_label (code, value, lang, type) values ('v', 'verb', 'eng', 'descrip');
insert into pos_label (code, value, lang, type) values ('x', 'X', 'est', 'capital');
insert into pos_label (code, value, lang, type) values ('adj', 'adj', 'lat', 'abbrev');
insert into pos_label (code, value, lang, type) values ('adv', 'adv', 'lat', 'abbrev');
insert into pos_label (code, value, lang, type) values ('adjg', 'adjg, ag', 'lat', 'abbrev');
insert into pos_label (code, value, lang, type) values ('interj', 'interj', 'lat', 'abbrev');
insert into pos_label (code, value, lang, type) values ('konj', 'konj', 'lat', 'abbrev');
insert into pos_label (code, value, lang, type) values ('postp', 'postp', 'lat', 'abbrev');
insert into pos_label (code, value, lang, type) values ('prep', 'prep', 'lat', 'abbrev');
insert into pos_label (code, value, lang, type) values ('num', 'num', 'lat', 'abbrev');
insert into pos_label (code, value, lang, type) values ('pron', 'pron', 'lat', 'abbrev');
insert into pos_label (code, value, lang, type) values ('s', 's', 'lat', 'abbrev');
insert into pos_label (code, value, lang, type) values ('v', 'v', 'lat', 'abbrev');
insert into pos_label (code, value, lang, type) values ('postp', 'postpositsioon, tagasõna', 'est', 'descrip');
insert into pos_label (code, value, lang, type) values ('prep', 'prepositsioon, eessõna', 'est', 'descrip');
insert into pos_label (code, value, lang, type) values ('x', 'erivormiline sõna', 'est', 'descrip');
insert into pos_label (code, value, lang, type) values ('postp', 'postposition', 'eng', 'descrip');
insert into pos_label (code, value, lang, type) values ('prep', 'preposition', 'eng', 'descrip');
insert into pos_label (code, value, lang, type) values ('prop', 'nimi', 'est', 'wordweb');
insert into pos_label (code, value, lang, type) values ('prep', 'eessõna', 'est', 'wordweb');
insert into pos_label (code, value, lang, type) values ('ord', 'järgarvsõna', 'est', 'wordweb');
insert into pos_label (code, value, lang, type) values ('postp', 'tagasõna', 'est', 'wordweb');
insert into pos_label (code, value, lang, type) values ('num', 'arvsõna', 'est', 'wordweb');
insert into pos_label (code, value, lang, type) values ('pron', 'asesõna', 'est', 'wordweb');
insert into pos_label (code, value, lang, type) values ('adj', 'omadussõna', 'est', 'wordweb');
insert into pos_label (code, value, lang, type) values ('adjg', 'täiendsõna', 'est', 'wordweb');
insert into pos_label (code, value, lang, type) values ('s', 'nimisõna', 'est', 'wordweb');
insert into pos_label (code, value, lang, type) values ('adv', 'määrsõna', 'est', 'wordweb');
insert into pos_label (code, value, lang, type) values ('v', 'tegusõna', 'est', 'wordweb');
insert into pos_label (code, value, lang, type) values ('interj', 'hüüdsõna', 'est', 'wordweb');
insert into pos_label (code, value, lang, type) values ('adp', 'kaassõna', 'est', 'wordweb');
insert into pos_label (code, value, lang, type) values ('konj', 'sidesõna', 'est', 'wordweb');
insert into pos_group_label (code, value, lang, type) values ('A', 'adjektiiv, omadussõnaga', 'est', 'descrip');
insert into pos_group_label (code, value, lang, type) values ('D', 'adverb, määrsõnaga', 'est', 'descrip');
insert into pos_group_label (code, value, lang, type) values ('H', 'prooprium, pärisnimega', 'est', 'descrip');
insert into pos_group_label (code, value, lang, type) values ('K', 'prep-postp, kaassõnaga', 'est', 'descrip');
insert into pos_group_label (code, value, lang, type) values ('N', 'numeraal, arvsõnaga', 'est', 'descrip');
insert into pos_group_label (code, value, lang, type) values ('S', 'substantiiv, nimisõnaga', 'est', 'descrip');
insert into pos_group_label (code, value, lang, type) values ('V', 'verb, tegusõnaga', 'est', 'descrip');
insert into pos_group_label (code, value, lang, type) values ('A', 'omadussõnaga', 'est', 'wordweb');
insert into pos_group_label (code, value, lang, type) values ('D', 'määrsõnaga', 'est', 'wordweb');
insert into pos_group_label (code, value, lang, type) values ('H', 'pärisnimega', 'est', 'wordweb');
insert into pos_group_label (code, value, lang, type) values ('K', 'kaassõnaga', 'est', 'wordweb');
insert into pos_group_label (code, value, lang, type) values ('N', 'arvsõnaga', 'est', 'wordweb');
insert into pos_group_label (code, value, lang, type) values ('S', 'nimisõnaga', 'est', 'wordweb');
insert into pos_group_label (code, value, lang, type) values ('V', 'tegusõnaga', 'est', 'wordweb');
insert into register_label (code, value, lang, type) values ('eevn', 'eestivene', 'est', 'descrip');
insert into register_label (code, value, lang, type) values ('hlv', 'halvustav, solvav', 'est', 'descrip');
insert into register_label (code, value, lang, type) values ('hlv', 'offensive', 'eng', 'descrip');
insert into register_label (code, value, lang, type) values ('hellitl', 'hellitlev', 'est', 'descrip');
insert into register_label (code, value, lang, type) values ('hrv', 'harvaesinev', 'est', 'descrip');
insert into register_label (code, value, lang, type) values ('hrv', 'rare', 'eng', 'descrip');
insert into register_label (code, value, lang, type) values ('kõrgst', 'kõrgstiil', 'est', 'descrip');
insert into register_label (code, value, lang, type) values ('lastek', 'lastekeelne', 'est', 'descrip');
insert into register_label (code, value, lang, type) values ('lastek', 'child language', 'eng', 'descrip');
insert into register_label (code, value, lang, type) values ('luulek', 'luulekeelne', 'est', 'descrip');
insert into register_label (code, value, lang, type) values ('luulek', 'poetic', 'eng', 'descrip');
insert into register_label (code, value, lang, type) values ('madalk', 'madalkeelne', 'est', 'descrip');
insert into register_label (code, value, lang, type) values ('murd', 'murdekeelne', 'est', 'descrip');
insert into register_label (code, value, lang, type) values ('murd', 'dialect, regional', 'eng', 'descrip');
insert into register_label (code, value, lang, type) values ('nlj', 'naljatlev', 'est', 'descrip');
insert into register_label (code, value, lang, type) values ('nlj', 'humorous', 'eng', 'descrip');
insert into register_label (code, value, lang, type) values ('piltl', 'piltlik', 'est', 'descrip');
insert into register_label (code, value, lang, type) values ('piltl', 'figurative', 'eng', 'descrip');
insert into register_label (code, value, lang, type) values ('släng', 'släng', 'est', 'descrip');
insert into register_label (code, value, lang, type) values ('släng', 'slang', 'eng', 'descrip');
insert into register_label (code, value, lang, type) values ('uudis', 'uudissõna, neologism', 'est', 'descrip');
insert into register_label (code, value, lang, type) values ('uudis', 'neologism', 'eng', 'descrip');
insert into register_label (code, value, lang, type) values ('kõnek', 'kõnekeelne, vabakeelne, mitteformaalne', 'est', 'descrip');
insert into register_label (code, value, lang, type) values ('kõnek', 'informal, journalistic', 'eng', 'descrip');
insert into register_label (code, value, lang, type) values ('van', 'vananenud, vananemas', 'est', 'descrip');
insert into register_label (code, value, lang, type) values ('van', 'archaic', 'eng', 'descrip');
insert into register_label (code, value, lang, type) values ('vulg', 'vulgaarne', 'est', 'descrip');
insert into register_label (code, value, lang, type) values ('vulg', 'vulgar', 'eng', 'descrip');
insert into register_label (code, value, lang, type) values ('eevn', 'eestivene', 'est', 'wordweb');
insert into register_label (code, value, lang, type) values ('hellitl', 'hellitlev', 'est', 'wordweb');
insert into register_label (code, value, lang, type) values ('hlv', 'halvustav', 'est', 'wordweb');
insert into register_label (code, value, lang, type) values ('hrv', 'harvaesinev', 'est', 'wordweb');
insert into register_label (code, value, lang, type) values ('kõrgst', 'kõrgstiil', 'est', 'wordweb');
insert into register_label (code, value, lang, type) values ('lastek', 'lastekeelne', 'est', 'wordweb');
insert into register_label (code, value, lang, type) values ('madalk', 'madalkeelne', 'est', 'wordweb');
insert into register_label (code, value, lang, type) values ('luulek', 'luulekeelne', 'est', 'wordweb');
insert into register_label (code, value, lang, type) values ('murd', 'murdes', 'est', 'wordweb');
insert into register_label (code, value, lang, type) values ('nlj', 'naljatlev', 'est', 'wordweb');
insert into register_label (code, value, lang, type) values ('piltl', 'piltlik', 'est', 'wordweb');
insert into register_label (code, value, lang, type) values ('släng', 'släng', 'est', 'wordweb');
insert into register_label (code, value, lang, type) values ('uudis', 'uudissõna', 'est', 'wordweb');
insert into register_label (code, value, lang, type) values ('van', 'vananenud', 'est', 'wordweb');
insert into register_label (code, value, lang, type) values ('vulg', 'vulgaarne', 'est', 'wordweb');
insert into register_label (code, value, lang, type) values ('kõnek', 'kõnekeelne', 'est', 'wordweb');
insert into usage_type_label (code, value, lang, type) values ('ls', 'liitsõna', 'est', 'descrip');
insert into usage_type_label (code, value, lang, type) values ('ls', 'compound', 'eng', 'descrip');
insert into usage_type_label (code, value, lang, type) values ('Vs', 'vanasõna', 'est', 'descrip');
insert into usage_type_label (code, value, lang, type) values ('Vs', 'proverb', 'eng', 'descrip');
insert into usage_type_label (code, value, lang, type) values ('y', 'sõnaühend', 'est', 'descrip');
insert into usage_type_label (code, value, lang, type) values ('y', 'sõnaühend', 'est', 'wordweb');
insert into usage_type_label (code, value, lang, type) values ('Vs', 'vanasõna', 'est', 'wordweb');
insert into value_state_label (code, value, lang, type) values ('eelistermin', 'eelistermin', 'est', 'descrip');
insert into value_state_label (code, value, lang, type) values ('eelistermin', 'preferred', 'eng', 'descrip');
insert into value_state_label (code, value, lang, type) values ('rööptermin', 'rööptermin', 'est', 'descrip');
insert into value_state_label (code, value, lang, type) values ('rööptermin', 'admitted', 'eng', 'descrip');
insert into value_state_label (code, value, lang, type) values ('variant', 'variant', 'est', 'descrip');
insert into value_state_label (code, value, lang, type) values ('variant', 'variant', 'eng', 'descrip');
insert into value_state_label (code, value, lang, type) values ('väldi', 'väldi', 'est', 'descrip');
insert into value_state_label (code, value, lang, type) values ('väldi', 'deprecated', 'eng', 'descrip');
insert into value_state_label (code, value, lang, type) values ('endine', 'endine', 'est', 'descrip');
insert into value_state_label (code, value, lang, type) values ('endine', 'superseded', 'eng', 'descrip');
insert into value_state_label (code, value, lang, type) values ('eelistermin', 'eelistermin', 'est', 'wordweb');
insert into value_state_label (code, value, lang, type) values ('endine', 'endine', 'est', 'wordweb');
insert into value_state_label (code, value, lang, type) values ('rööptermin', 'rööptermin', 'est', 'wordweb');
insert into value_state_label (code, value, lang, type) values ('väldi', 'väldi', 'est', 'wordweb');
insert into word_rel_type_label (code, value, lang, type) values ('posit', 'algvõrre', 'est', 'full');
insert into word_rel_type_label (code, value, lang, type) values ('deriv_base', 'tuletusalus', 'est', 'full');
insert into word_rel_type_label (code, value, lang, type) values ('komp', 'keskvõrre', 'est', 'full');
insert into word_rel_type_label (code, value, lang, type) values ('superl', 'ülivõrre', 'est', 'full');
insert into word_rel_type_label (code, value, lang, type) values ('deriv', 'tuletis', 'est', 'full');
insert into word_rel_type_label (code, value, lang, type) values ('SERIES', 'sari', 'est', 'full');
insert into word_rel_type_label (code, value, lang, type) values ('VARIANTS', 'variandid', 'est', 'full');
insert into word_rel_type_label (code, value, lang, type) values ('posit', 'algvõrre', 'est', 'wordweb');
insert into word_rel_type_label (code, value, lang, type) values ('komp', 'keskvõrre', 'est', 'wordweb');
insert into word_rel_type_label (code, value, lang, type) values ('deriv', 'tuletis', 'est', 'wordweb');
insert into word_rel_type_label (code, value, lang, type) values ('deriv_base', 'tuletusalus', 'est', 'wordweb');
insert into word_rel_type_label (code, value, lang, type) values ('superl', 'ülivõrre', 'est', 'wordweb');
insert into word_rel_type_label (code, value, lang, type) values ('SERIES', 'sari', 'est', 'wordweb');
insert into word_rel_type_label (code, value, lang, type) values ('VARIANTS', 'variandid', 'est', 'wordweb');
insert into word_type_label (code, value, lang, type) values ('k', 'kohanimi', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('k', 'place name', 'eng', 'descrip');
insert into word_type_label (code, value, lang, type) values ('l', 'lühend', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('l', 'abbreviation', 'eng', 'descrip');
insert into word_type_label (code, value, lang, type) values ('p', 'pärisnimi', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('p', 'proper name', 'eng', 'descrip');
insert into word_type_label (code, value, lang, type) values ('z', 'tsitaatsõna', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('z', 'loanword (alien)', 'eng', 'descrip');
insert into word_type_label (code, value, lang, type) values ('mvv', 'viiteartikli märksõna', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('yv', 'ühendverb', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('vv', 'väljendverb', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('av', 'ahelverb', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('tv', 'tugiverb', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('vlj', 'väljend', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('ys', 'ühendsidesõna (nii et)', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('rs', 'rühmsidesõna (ei .. ega)', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('f', 'fras-väljend (väljendite plokis)', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('f', '(idiomatic) phrase (grp)', 'eng', 'descrip');
insert into word_type_label (code, value, lang, type) values ('mf', 'märksõna-väljend (iseseisev)', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('mf', 'multiword unit (in the alphabet)', 'eng', 'descrip');
insert into word_type_label (code, value, lang, type) values ('g', 'omastavaline täiend, genitiivne täiend', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('lz', 'tsitaatsõna lühend', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('lz', 'abbreviation for alien word', 'eng', 'descrip');
insert into word_type_label (code, value, lang, type) values ('n', 'number (nt 24/7)', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('n', 'number', 'eng', 'descrip');
insert into word_type_label (code, value, lang, type) values ('pf', 'prefiksoid, pooleesliide vm esiosa', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('pf', 'combining form', 'eng', 'descrip');
insert into word_type_label (code, value, lang, type) values ('s', 'sarja liige', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('s', 'serial member', 'eng', 'descrip');
insert into word_type_label (code, value, lang, type) values ('km', 'kaubamärk', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('th', 'tähis', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('valem', 'valem', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('termin', 'termin', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('tõlkeprobleem', 'tõlkeprobleem', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('ametinimetus', 'ametinimetus', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('organisatsiooni, asutuse nimi', 'organisatsiooni, asutuse nimi', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('õigusakti pealkiri', 'õigusakti pealkiri', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('dokumendi pealkiri', 'dokumendi pealkiri', 'est', 'descrip');
insert into word_type_label (code, value, lang, type) values ('l', 'lühend', 'est', 'wordweb');
insert into word_type_label (code, value, lang, type) values ('km', 'kaubamärk', 'est', 'wordweb');
insert into word_type_label (code, value, lang, type) values ('k', 'kohanimi', 'est', 'wordweb');
insert into word_type_label (code, value, lang, type) values ('lz', 'lühend', 'est', 'wordweb');
insert into word_type_label (code, value, lang, type) values ('th', 'tähis', 'est', 'wordweb');
insert into word_type_label (code, value, lang, type) values ('ametinimetus', 'ametinimetus', 'est', 'wordweb');
insert into word_type_label (code, value, lang, type) values ('dokumendi pealkiri', 'dokumendi pealkiri', 'est', 'wordweb');
insert into word_type_label (code, value, lang, type) values ('õigusakti pealkiri', 'õigusakti pealkiri', 'est', 'wordweb');
insert into word_type_label (code, value, lang, type) values ('organisatsiooni, asutuse nimi', 'organisatsiooni, asutuse nimi', 'est', 'wordweb');
insert into word_type_label (code, value, lang, type) values ('termin', 'termin', 'est', 'wordweb');
insert into word_type_label (code, value, lang, type) values ('tõlkeprobleem', 'tõlkeprobleem', 'est', 'wordweb');
insert into word_type_label (code, value, lang, type) values ('valem', 'valem', 'est', 'wordweb');
