insert into label_type (code, value) values ('capital', 'capital');
insert into label_type (code, value) values ('abbrev', 'abbrev');
insert into label_type (code, value) values ('ekimorfo', 'ekimorfo');
insert into label_type (code, value) values ('descrip', 'descrip');
insert into label_type (code, value) values ('descrip2', 'descrip2');
insert into label_type (code, value) values ('full', 'full');
insert into label_type (code, value) values ('wordweb', 'wordweb');

-- lex
insert into dataset (code, name, is_public) values ('ss1', 'Eesti keele sõnaraamat 2019', true);
insert into dataset (code, name, is_public) values ('psv', 'Eesti keele põhisõnavara sõnastik 2014', true);
insert into dataset (code, name, is_public) values ('ety',	'Etümoloogia', true);
insert into dataset (code, name, is_public) values ('qq2', 'Eesti-vene õpilase ÕS 2019', true);
insert into dataset (code, name, is_public) values ('ev2',	'Eesti-vene sõnaraamat 2019', true);
insert into dataset (code, name, is_public) values ('kol',	'Eesti keele naabersõnad 2019', true);
insert into dataset (code, name, is_public) values ('mab', 'Eesti keele morfoloogia', false);

-- term
insert into dataset (code, name, is_public) values ('est', 'Esterm', true);
insert into dataset (code, name, is_public) values ('aia',	'Aiandus (aiandusterminoloogia sõnastik)', true);
insert into dataset (code, name, is_public) values ('ait',	'Aianduse terminibaas (2017)', true);
insert into dataset (code, name, is_public) values ('avt',	'Akadeemilise väljendusoskuse terminid', true);
insert into dataset (code, name, is_public) values ('aso',	'Andmeanalüüsi ja statistika oskussõnastik', true);
insert into dataset (code, name, is_public) values ('arh',	'Arheoloogia terminibaas', true);
insert into dataset (code, name, is_public) values ('aos',	'Arhitektuuri oskussõnastik', true);
insert into dataset (code, name, is_public) values ('den',	'Dental Technique Terminology', true);
insert into dataset (code, name, is_public) values ('eõt',	'E-õppe termineid', true);
insert into dataset (code, name, is_public) values ('ett',	'Eesti E-tervise SA terminibaas', true);
insert into dataset (code, name, is_public) values ('õtb',	'Eesti-vene-eesti õigusterminoloogiabaas', true);
insert into dataset (code, name, is_public) values ('ent',	'Entomoloogia', true);
insert into dataset (code, name, is_public) values ('fil',	'Filosoofia', true);
insert into dataset (code, name, is_public) values ('fkm',	'Filmikunsti mõisted', true);
insert into dataset (code, name, is_public) values ('fon',	'Foneetika', true);
insert into dataset (code, name, is_public) values ('get',	'Geoloogia', true);
insert into dataset (code, name, is_public) values ('gmt',	'Geomorfoloogia', true);
insert into dataset (code, name, is_public) values ('ida',	'Ida mõtteloo leksikon', true);
insert into dataset (code, name, is_public) values ('iht',	'Ihtüoloogia', true);
insert into dataset (code, name, is_public) values ('bks',	'Inglise-eesti biokeemia sõnastik', true);
insert into dataset (code, name, is_public) values ('kto',	'Käsitööteaduse oskussõnad', true);
insert into dataset (code, name, is_public) values ('kem',	'Keemiatermite baas', true);
insert into dataset (code, name, is_public) values ('kkt',	'Kognitiivse keeleteaduse terminibaas', true);
insert into dataset (code, name, is_public) values ('kok',	'Kokandus', true);
insert into dataset (code, name, is_public) values ('kfs',	'Küberfüüsikalise süsteemitehnika terminibaas', true);
insert into dataset (code, name, is_public) values ('lim',	'Limnoloogia sõnastik', true);
insert into dataset (code, name, is_public) values ('lkt',	'Loomakasvatus', true);
insert into dataset (code, name, is_public) values ('lon',	'Loomanimed', true);
insert into dataset (code, name, is_public) values ('pre',	'Loomaparasiitide eestipärased nimetused', true);
insert into dataset (code, name, is_public) values ('lpr',	'Loomaparasiitide nimistu', true);
insert into dataset (code, name, is_public) values ('lko',	'Loomi kaasavate organisatsioonide terminibaas', true);
insert into dataset (code, name, is_public) values ('mef',	'Meditsiinifüüsika', true);
insert into dataset (code, name, is_public) values ('mes',	'Mesindusleksikon', true);
insert into dataset (code, name, is_public) values ('met',	'MetalliAabits', true);
insert into dataset (code, name, is_public) values ('mea',	'Metroloogia', true);
insert into dataset (code, name, is_public) values ('mut',	'Muuseumiterminoloogia', true);
insert into dataset (code, name, is_public) values ('mte',	'Muusikateraapia seletav sõnastik', true);
insert into dataset (code, name, is_public) values ('nht',	'Nahkhiirte-alased terminid', true);
insert into dataset (code, name, is_public) values ('prs',	'Parasitoloogia terminid', true);
insert into dataset (code, name, is_public) values ('pot',	'Patsiendiohutuse terminibaas', true);
insert into dataset (code, name, is_public) values ('pol',	'Poliitika ja valitsemise sõnastik', true);
insert into dataset (code, name, is_public) values ('pur',	'Purjetamise terminoloogia', true);
insert into dataset (code, name, is_public) values ('p3m',	'P3M (Projektide, programmide ja portfellide juhtimise mõistete baas)', true);
insert into dataset (code, name, is_public) values ('tee',	'Teenuste valdkonna terminibaas', true);
insert into dataset (code, name, is_public) values ('tts',	'Tootmistehnika ja süsteemide terminibaas', true);
insert into dataset (code, name, is_public) values ('usk',	'Uskumusolendite sõnastik', true);
insert into dataset (code, name, is_public) values ('ust',	'Usterm', true);
insert into dataset (code, name, is_public) values ('vlk',	'Veterinaarmeditsiin ja loomakasvatus', true);

