insert into lang (code, value) values ('est', 'Estonian');
insert into lang (code, value) values ('eng', 'English');
insert into lang (code, value) values ('rus', 'Russian');
insert into lang (code, value) values ('fra', 'French');
insert into lang (code, value) values ('deu', 'German');
insert into lang (code, value) values ('fin', 'Finnish');
insert into lang (code, value) values ('lat', 'Latin');
insert into lang (code, value) values ('pol', 'Polish');
insert into lang (code, value) values ('lav', 'Latvian');
insert into lang (code, value) values ('swe', 'Swedish');
insert into lang (code, value) values ('nld', 'Dutch');
insert into lang (code, value) values ('san', 'Sanskrit');
insert into lang (code, value) values ('pli', 'Pali');
insert into lang (code, value) values ('zho', 'Chinese');
insert into lang (code, value) values ('jpn', 'Japanese');
insert into lang (code, value) values ('bod', 'Tibetan');
insert into lang (code, value) values ('hin', 'Hindi');
insert into lang (code, value) values ('pan', 'Panjabi');
insert into lang (code, value) values ('ell', 'Greek');
insert into lang (code, value) values ('spa', 'Spanish');
insert into lang (code, value) values ('dan', 'Danish');

insert into label_type (code, value) values ('capital', 'capital');
insert into label_type (code, value) values ('abbrev', 'abbrev');
insert into label_type (code, value) values ('ekimorfo', 'ekimorfo');
insert into label_type (code, value) values ('descrip', 'descrip');
insert into label_type (code, value) values ('descrip2', 'descrip2');
insert into label_type (code, value) values ('full', 'full');

insert into dataset (code, name) values ('qq2', 'Eesti-vene õpilase ÕS (2011)');
insert into dataset (code, name) values ('psv', 'Õppesõnastik A2/B1: eesti keele põhisõnavara (2014)');
insert into dataset (code, name) values ('ss1', 'Eesti keele (üheköiteline) sõnaraamat (2010-2018/2019)');
insert into dataset (code, name) values ('kol',	'Kollokatsioonid');
insert into dataset (code, name) values ('ev2',	'Eesti-vene');
insert into dataset (code, name) values ('est', 'Esterm');
insert into dataset (code, name) values ('aia',	'Aiandus (aiandusterminoloogia sõnastik)');
insert into dataset (code, name) values ('avt',	'Akadeemilise väljendusoskuse terminid');
insert into dataset (code, name) values ('aso',	'Andmeanalüüsi ja statistika oskussõnastik');
insert into dataset (code, name) values ('arh',	'Arheoloogia terminibaas');
insert into dataset (code, name) values ('aos',	'Arhitektuuri oskussõnastik');
insert into dataset (code, name) values ('den',	'Dental Technique Terminology');
insert into dataset (code, name) values ('eõt',	'E-õppe termineid');
insert into dataset (code, name) values ('ett',	'Eesti E-tervise SA terminibaas');
insert into dataset (code, name) values ('ent',	'Entomoloogia');
insert into dataset (code, name) values ('fil',	'Filosoofia');
insert into dataset (code, name) values ('get',	'Geoloogia');
insert into dataset (code, name) values ('gmt',	'Geomorfoloogia');
insert into dataset (code, name) values ('ida',	'Ida mõtteloo leksikon');
insert into dataset (code, name) values ('iht',	'Ihtüoloogia');
insert into dataset (code, name) values ('bks',	'Inglise-eesti biokeemia sõnastik');
insert into dataset (code, name) values ('kto',	'Käsitööteaduse oskussõnad');
insert into dataset (code, name) values ('kem',	'Keemiatermite baas');
insert into dataset (code, name) values ('kkt',	'Kognitiivse keeleteaduse terminibaas');
insert into dataset (code, name) values ('kok',	'Kokandus');
insert into dataset (code, name) values ('kfs',	'Küberfüüsikalise süsteemitehnika terminibaas');
insert into dataset (code, name) values ('lim',	'Limnoloogia sõnastik');
insert into dataset (code, name) values ('lkt',	'Loomakasvatus');
insert into dataset (code, name) values ('lon',	'Loomanimed');
insert into dataset (code, name) values ('pre',	'Loomaparasiitide eestipärased nimetused');
insert into dataset (code, name) values ('lpr',	'Loomaparasiitide nimistu');
insert into dataset (code, name) values ('lko',	'Loomi kaasavate organisatsioonide terminibaas');
insert into dataset (code, name) values ('mef',	'Meditsiinifüüsika');
insert into dataset (code, name) values ('met',	'MetalliAabits');
insert into dataset (code, name) values ('mea',	'Metroloogia');
insert into dataset (code, name) values ('mut',	'Muuseumiterminoloogia');
insert into dataset (code, name) values ('mte',	'Muusikateraapia seletav sõnastik');
insert into dataset (code, name) values ('nht',	'Nahkhiirte-alased terminid');
insert into dataset (code, name) values ('prs',	'Parasitoloogia terminid');
insert into dataset (code, name) values ('pol',	'Poliitika ja valitsemise sõnastik');
insert into dataset (code, name) values ('tee',	'Teenuste valdkonna terminibaas');
insert into dataset (code, name) values ('tts',	'Tootmistehnika ja süsteemide terminibaas');
insert into dataset (code, name) values ('usk',	'Uskumusolendite sõnastik');
insert into dataset (code, name) values ('vlk',	'Veterinaarmeditsiin ja loomakasvatus');
insert into dataset (code, name) values ('ait',	'Aianduse terminibaas (2017)');
insert into dataset (code, name) values ('õtb',	'Eesti-vene-eesti õigusterminoloogiabaas');
insert into dataset (code, name) values ('fkm',	'Filmikunstimõisted');
insert into dataset (code, name) values ('fon',	'Foneetika');
insert into dataset (code, name) values ('mes',	'Mesindusleksikon');
insert into dataset (code, name) values ('p3m',	'P3M (Projektide, programmide ja portfellide juhtimise mõistete baas)');
insert into dataset (code, name) values ('pot',	'Patsiendiohutuse terminibaas');
insert into dataset (code, name) values ('pur',	'Purjetamise terminoloogia');
insert into dataset (code, name) values ('ust',	'Usterm');
