insert into label_type (code, value) values ('capital', 'capital');
insert into label_type (code, value) values ('abbrev', 'abbrev');
insert into label_type (code, value) values ('ekimorfo', 'ekimorfo');
insert into label_type (code, value) values ('descrip', 'descrip');
insert into label_type (code, value) values ('descrip2', 'descrip2');
insert into label_type (code, value) values ('full', 'full');
insert into label_type (code, value) values ('wordweb', 'wordweb');

insert into dataset (code, name) values ('ss1', 'Eesti keele sõnaraamat 2018');
insert into dataset (code, name) values ('psv', 'Õppesõnastik A2/B1: eesti keele põhisõnavara (2014)');
insert into dataset (code, name) values ('kol',	'Kollokatsioonid');
insert into dataset (code, name) values ('ety',	'Etümoloogia');
insert into dataset (code, name) values ('qq2', 'Eesti-vene õpilase ÕS (2011)');
insert into dataset (code, name) values ('ev2',	'Eesti-vene');
insert into dataset (code, name) values ('est', 'Esterm');
insert into dataset (code, name) values ('aia',	'Aiandus (aiandusterminoloogia sõnastik)');
insert into dataset (code, name) values ('avt',	'Akadeemilise väljendusoskuse terminid');
insert into dataset (code, name) values ('aso',	'Andmeanalüüsi ja statistika oskussõnastik');
insert into dataset (code, name) values ('arh',	'Arheoloogia terminibaas');
insert into dataset (code, name) values ('aos',	'Arhitektuuri oskussõnastik');
insert into dataset (code, name) values ('den',	'Dental Technique Terminology');
insert into dataset (code, name) values ('eõt',	'E-õppe termineid');
insert into dataset (code, name) values ('ett',	'Eesti E-tervise SA terminibaas');
insert into dataset (code, name) values ('ent',	'Entomoloogia');
insert into dataset (code, name) values ('fil',	'Filosoofia');
insert into dataset (code, name) values ('get',	'Geoloogia');
insert into dataset (code, name) values ('gmt',	'Geomorfoloogia');
insert into dataset (code, name) values ('ida',	'Ida mõtteloo leksikon');
insert into dataset (code, name) values ('iht',	'Ihtüoloogia');
insert into dataset (code, name) values ('bks',	'Inglise-eesti biokeemia sõnastik');
insert into dataset (code, name) values ('kto',	'Käsitööteaduse oskussõnad');
insert into dataset (code, name) values ('kem',	'Keemiatermite baas');
insert into dataset (code, name) values ('kkt',	'Kognitiivse keeleteaduse terminibaas');
insert into dataset (code, name) values ('kok',	'Kokandus');
insert into dataset (code, name) values ('kfs',	'Küberfüüsikalise süsteemitehnika terminibaas');
insert into dataset (code, name) values ('lim',	'Limnoloogia sõnastik');
insert into dataset (code, name) values ('lkt',	'Loomakasvatus');
insert into dataset (code, name) values ('lon',	'Loomanimed');
insert into dataset (code, name) values ('pre',	'Loomaparasiitide eestipärased nimetused');
insert into dataset (code, name) values ('lpr',	'Loomaparasiitide nimistu');
insert into dataset (code, name) values ('lko',	'Loomi kaasavate organisatsioonide terminibaas');
insert into dataset (code, name) values ('mef',	'Meditsiinifüüsika');
insert into dataset (code, name) values ('met',	'MetalliAabits');
insert into dataset (code, name) values ('mea',	'Metroloogia');
insert into dataset (code, name) values ('mut',	'Muuseumiterminoloogia');
insert into dataset (code, name) values ('mte',	'Muusikateraapia seletav sõnastik');
insert into dataset (code, name) values ('nht',	'Nahkhiirte-alased terminid');
insert into dataset (code, name) values ('prs',	'Parasitoloogia terminid');
insert into dataset (code, name) values ('pol',	'Poliitika ja valitsemise sõnastik');
insert into dataset (code, name) values ('tee',	'Teenuste valdkonna terminibaas');
insert into dataset (code, name) values ('tts',	'Tootmistehnika ja süsteemide terminibaas');
insert into dataset (code, name) values ('usk',	'Uskumusolendite sõnastik');
insert into dataset (code, name) values ('vlk',	'Veterinaarmeditsiin ja loomakasvatus');
insert into dataset (code, name) values ('ait',	'Aianduse terminibaas (2017)');
insert into dataset (code, name) values ('õtb',	'Eesti-vene-eesti õigusterminoloogiabaas');
insert into dataset (code, name) values ('fkm',	'Filmikunstimõisted');
insert into dataset (code, name) values ('fon',	'Foneetika');
insert into dataset (code, name) values ('mes',	'Mesindusleksikon');
insert into dataset (code, name) values ('p3m',	'P3M (Projektide, programmide ja portfellide juhtimise mõistete baas)');
insert into dataset (code, name) values ('pot',	'Patsiendiohutuse terminibaas');
insert into dataset (code, name) values ('pur',	'Purjetamise terminoloogia');
insert into dataset (code, name) values ('ust',	'Usterm');

-- TODO to be removed later once the languages are imported as other classifiers
insert into language (code, datasets) values ('est', '{}');
insert into language (code, datasets) values ('eng', '{}');
insert into language (code, datasets) values ('rus', '{}');
insert into language (code, datasets) values ('fra', '{}');
insert into language (code, datasets) values ('deu', '{}');
insert into language (code, datasets) values ('fin', '{}');
insert into language (code, datasets) values ('lat', '{}');
insert into language (code, datasets) values ('pol', '{}');
insert into language (code, datasets) values ('lav', '{}');
insert into language (code, datasets) values ('swe', '{}');
insert into language (code, datasets) values ('nld', '{}');
insert into language (code, datasets) values ('san', '{}');
insert into language (code, datasets) values ('pli', '{}');
insert into language (code, datasets) values ('zho', '{}');
insert into language (code, datasets) values ('jpn', '{}');
insert into language (code, datasets) values ('bod', '{}');
insert into language (code, datasets) values ('hin', '{}');
insert into language (code, datasets) values ('pan', '{}');
insert into language (code, datasets) values ('ell', '{}');
insert into language (code, datasets) values ('spa', '{}');
insert into language (code, datasets) values ('dan', '{}');
insert into language (code, datasets) values ('---', '{}');

insert into language_label (code, value, lang, type) values ('est', 'Estonian', 'est', 'descrip');
insert into language_label (code, value, lang, type) values ('eng', 'English', 'est', 'descrip');
insert into language_label (code, value, lang, type) values ('rus', 'Russian', 'est', 'descrip');
insert into language_label (code, value, lang, type) values ('fra', 'French', 'est', 'descrip');
insert into language_label (code, value, lang, type) values ('deu', 'German', 'est', 'descrip');
insert into language_label (code, value, lang, type) values ('fin', 'Finnish', 'est', 'descrip');
insert into language_label (code, value, lang, type) values ('lat', 'Latin', 'est', 'descrip');
insert into language_label (code, value, lang, type) values ('pol', 'Polish', 'est', 'descrip');
insert into language_label (code, value, lang, type) values ('lav', 'Latvian', 'est', 'descrip');
insert into language_label (code, value, lang, type) values ('swe', 'Swedish', 'est', 'descrip');
insert into language_label (code, value, lang, type) values ('nld', 'Dutch', 'est', 'descrip');
insert into language_label (code, value, lang, type) values ('san', 'Sanskrit', 'est', 'descrip');
insert into language_label (code, value, lang, type) values ('pli', 'Pali', 'est', 'descrip');
insert into language_label (code, value, lang, type) values ('zho', 'Chinese', 'est', 'descrip');
insert into language_label (code, value, lang, type) values ('jpn', 'Japanese', 'est', 'descrip');
insert into language_label (code, value, lang, type) values ('bod', 'Tibetan', 'est', 'descrip');
insert into language_label (code, value, lang, type) values ('hin', 'Hindi', 'est', 'descrip');
insert into language_label (code, value, lang, type) values ('pan', 'Panjabi', 'est', 'descrip');
insert into language_label (code, value, lang, type) values ('ell', 'Greek', 'est', 'descrip');
insert into language_label (code, value, lang, type) values ('spa', 'Spanish', 'est', 'descrip');
insert into language_label (code, value, lang, type) values ('dan', 'Danish', 'est', 'descrip');
insert into language_label (code, value, lang, type) values ('---', 'N/A', 'est', 'descrip');
