create index lexeme_tag_tag_name_lower_idx on lexeme_tag(lower(tag_name));
create index meaning_tag_tag_name_lower_idx on meaning_tag(lower(tag_name));

insert into domain (code, origin, datasets) values ('ajal', 'har', '{}');
insert into domain (code, origin, datasets) values ('alus', 'har', '{}');
insert into domain (code, origin, datasets) values ('andr', 'har', '{}');
insert into domain (code, origin, datasets) values ('did', 'har', '{}');
insert into domain (code, origin, datasets) values ('erip', 'har', '{}');
insert into domain (code, origin, datasets) values ('filos', 'har', '{}');
insert into domain (code, origin, datasets) values ('huvi', 'har', '{}');
insert into domain (code, origin, datasets) values ('info', 'har', '{}');
insert into domain (code, origin, datasets) values ('isik', 'har', '{}');
insert into domain (code, origin, datasets) values ('kasv', 'har', '{}');
insert into domain (code, origin, datasets) values ('kord', 'har', '{}');
insert into domain (code, origin, datasets) values ('kutse', 'har', '{}');
insert into domain (code, origin, datasets) values ('kõrg', 'har', '{}');
insert into domain (code, origin, datasets) values ('org', 'har', '{}');
insert into domain (code, origin, datasets) values ('psühh', 'har', '{}');
insert into domain (code, origin, datasets) values ('sope', 'har', '{}');
insert into domain (code, origin, datasets) values ('sots', 'har', '{}');
insert into domain (code, origin, datasets) values ('tead', 'har', '{}');
insert into domain (code, origin, datasets) values ('vah', 'har', '{}');
insert into domain_label (code, origin, value, lang, type) values ('ajal', 'har', 'pedagoogika (kasvatuse, hariduse) ajalugu', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('alus', 'har', 'alusharidus (koolieelne haridus)', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('andr', 'har', 'andragoogika (täiskasvanuharidus; täiendusõpe)', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('did', 'har', 'didaktika', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('erip', 'har', 'eripedagoogika', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('filos', 'har', 'filosoofia', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('huvi', 'har', 'huviharidus', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('info', 'har', 'informaatika, e-õpe', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('isik', 'har', 'isikud', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('kasv', 'har', 'kasvatus ja areng (kasvatusmeetodid)', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('kord', 'har', 'koolikorraldus (hariduspoliitika, haridussüsteem, asutused)', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('kutse', 'har', 'kutseharidus', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('kõrg', 'har', 'kõrgharidus', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('org', 'har', 'organisatsioonid, institutsioonid, sh allüksused (nt metoodikakabinet)', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('psühh', 'har', 'psühholoogia, loogika', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('sope', 'har', 'sotsiaalpedagoogika', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('sots', 'har', 'haridussotsioloogia', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('tead', 'har', 'kasvatusteadus (uurimistööd jm)', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('vah', 'har', 'õppevahendid (sh ruumid)', 'est', 'descrip');

insert into domain (code, origin, datasets) values ('arv', 'has', '{}');
insert into domain (code, origin, datasets) values ('foto', 'has', '{}');
insert into domain (code, origin, datasets) values ('kino', 'has', '{}');
insert into domain (code, origin, datasets) values ('kirj', 'has', '{}');
insert into domain (code, origin, datasets) values ('koll', 'has', '{}');
insert into domain (code, origin, datasets) values ('kunst', 'has', '{}');
insert into domain (code, origin, datasets) values ('käsi', 'has', '{}');
insert into domain (code, origin, datasets) values ('loome', 'has', '{}');
insert into domain (code, origin, datasets) values ('muus', 'has', '{}');
insert into domain (code, origin, datasets) values ('nupu', 'has', '{}');
insert into domain (code, origin, datasets) values ('selts', 'has', '{}');
insert into domain (code, origin, datasets) values ('sport', 'has', '{}');
insert into domain (code, origin, datasets) values ('tants', 'has', '{}');
insert into domain (code, origin, datasets) values ('teat', 'has', '{}');
insert into domain (code, origin, datasets) values ('tehn', 'has', '{}');
insert into domain (code, origin, datasets) values ('terv', 'has', '{}');
insert into domain (code, origin, datasets) values ('vaba', 'has', '{}');
insert into domain (code, origin, datasets) values ('video', 'has', '{}');
insert into domain (code, origin, datasets) values ('üld', 'has', '{}');
insert into domain_label (code, origin, value, lang, type) values ('arv', 'has', 'arvuti', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('foto', 'has', 'fotograafia', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('kino', 'has', 'kino (amatöör-, animatsioon)', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('kirj', 'has', 'kirjandus', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('koll', 'has', 'kollektsioneerimine', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('kunst', 'has', 'kujutav kunst', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('käsi', 'has', 'käsitöö', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('loome', 'has', 'loometöö (nt luulelaagrid)', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('muus', 'has', 'muusika', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('nupu', 'has', 'nuputamine (ristsõnad, sudokud, pusled, alias jne)', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('selts', 'has', 'seltskondlikud mängud (lauamängud)', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('sport', 'has', 'sport (tervise-, võistlus-, ekstreem-) ja võitluskunstid', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('tants', 'has', 'tants (hiphop, ballett jne)', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('teat', 'has', 'teater', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('tehn', 'has', 'tehnika', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('terv', 'has', 'tervis', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('vaba', 'has', 'koolieelsed vabamängud', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('video', 'has', 'video- ja rollimängud', 'est', 'descrip');
insert into domain_label (code, origin, value, lang, type) values ('üld', 'has', 'üldmõisted (asutused, meetodid)', 'est', 'descrip');


