package eki.ekilex.constant;

public enum SearchOperand {

	EQUALS, STARTS_WITH, ENDS_WITH, CONTAINS, GREATER_THAN, LESS_THAN, CONTAINS_WORD, EXISTS, NOT_EXISTS, EARLIER_THAN, LATER_THAN, HAS_BEEN,
	ZERO, MORE_THAN_ZERO, ONE, MORE_THAN_ONE
}
