/*
 * This file is generated by jOOQ.
 */
package eki.wwexam.data.db.tables;


import eki.wwexam.data.db.Public;
import eki.wwexam.data.db.tables.records.WwClassifierRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WwClassifier extends TableImpl<WwClassifierRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ww_classifier</code>
     */
    public static final WwClassifier WW_CLASSIFIER = new WwClassifier();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WwClassifierRecord> getRecordType() {
        return WwClassifierRecord.class;
    }

    /**
     * The column <code>public.ww_classifier.name</code>.
     */
    public final TableField<WwClassifierRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.ww_classifier.code</code>.
     */
    public final TableField<WwClassifierRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.ww_classifier.value</code>.
     */
    public final TableField<WwClassifierRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.ww_classifier.lang</code>.
     */
    public final TableField<WwClassifierRecord, String> LANG = createField(DSL.name("lang"), SQLDataType.CHAR(3).nullable(false), this, "");

    /**
     * The column <code>public.ww_classifier.type</code>.
     */
    public final TableField<WwClassifierRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>public.ww_classifier.order_by</code>.
     */
    public final TableField<WwClassifierRecord, Long> ORDER_BY = createField(DSL.name("order_by"), SQLDataType.BIGINT.nullable(false), this, "");

    private WwClassifier(Name alias, Table<WwClassifierRecord> aliased) {
        this(alias, aliased, null);
    }

    private WwClassifier(Name alias, Table<WwClassifierRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.ww_classifier</code> table reference
     */
    public WwClassifier(String alias) {
        this(DSL.name(alias), WW_CLASSIFIER);
    }

    /**
     * Create an aliased <code>public.ww_classifier</code> table reference
     */
    public WwClassifier(Name alias) {
        this(alias, WW_CLASSIFIER);
    }

    /**
     * Create a <code>public.ww_classifier</code> table reference
     */
    public WwClassifier() {
        this(DSL.name("ww_classifier"), null);
    }

    public <O extends Record> WwClassifier(Table<O> child, ForeignKey<O, WwClassifierRecord> key) {
        super(child, key, WW_CLASSIFIER);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public WwClassifier as(String alias) {
        return new WwClassifier(DSL.name(alias), this);
    }

    @Override
    public WwClassifier as(Name alias) {
        return new WwClassifier(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WwClassifier rename(String name) {
        return new WwClassifier(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WwClassifier rename(Name name) {
        return new WwClassifier(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, String, String, String, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
