/*
 * This file is generated by jOOQ.
*/
package eki.wordweb.data.db.udt.records;


import eki.wordweb.data.db.udt.DblinkPkeyResults;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UDTRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DblinkPkeyResultsRecord extends UDTRecordImpl<DblinkPkeyResultsRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 129418915;

    /**
     * Setter for <code>public.dblink_pkey_results.position</code>.
     */
    public void setPosition(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.dblink_pkey_results.position</code>.
     */
    public Integer getPosition() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.dblink_pkey_results.colname</code>.
     */
    public void setColname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.dblink_pkey_results.colname</code>.
     */
    public String getColname() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DblinkPkeyResults.POSITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DblinkPkeyResults.COLNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getColname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getColname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DblinkPkeyResultsRecord value1(Integer value) {
        setPosition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DblinkPkeyResultsRecord value2(String value) {
        setColname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DblinkPkeyResultsRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DblinkPkeyResultsRecord
     */
    public DblinkPkeyResultsRecord() {
        super(DblinkPkeyResults.DBLINK_PKEY_RESULTS);
    }

    /**
     * Create a detached, initialised DblinkPkeyResultsRecord
     */
    public DblinkPkeyResultsRecord(Integer position, String colname) {
        super(DblinkPkeyResults.DBLINK_PKEY_RESULTS);

        set(0, position);
        set(1, colname);
    }
}
