/*
 * This file is generated by jOOQ.
 */
package eki.wordweb.data.db.udt.records;


import eki.wordweb.data.db.udt.TypeMeaningRelation;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UDTRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TypeMeaningRelationRecord extends UDTRecordImpl<TypeMeaningRelationRecord> implements Record8<Long, Long, Long, String, String, Integer, String, String> {

    private static final long serialVersionUID = -862347210;

    /**
     * Setter for <code>public.type_meaning_relation.meaning_id</code>.
     */
    public void setMeaningId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.type_meaning_relation.meaning_id</code>.
     */
    public Long getMeaningId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.type_meaning_relation.lexeme_id</code>.
     */
    public void setLexemeId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.type_meaning_relation.lexeme_id</code>.
     */
    public Long getLexemeId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.type_meaning_relation.word_id</code>.
     */
    public void setWordId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.type_meaning_relation.word_id</code>.
     */
    public Long getWordId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.type_meaning_relation.word</code>.
     */
    public void setWord(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.type_meaning_relation.word</code>.
     */
    public String getWord() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.type_meaning_relation.word_lang</code>.
     */
    public void setWordLang(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.type_meaning_relation.word_lang</code>.
     */
    public String getWordLang() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.type_meaning_relation.homonym_nr</code>.
     */
    public void setHomonymNr(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.type_meaning_relation.homonym_nr</code>.
     */
    public Integer getHomonymNr() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.type_meaning_relation.complexity</code>.
     */
    public void setComplexity(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.type_meaning_relation.complexity</code>.
     */
    public String getComplexity() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.type_meaning_relation.meaning_rel_type_code</code>.
     */
    public void setMeaningRelTypeCode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.type_meaning_relation.meaning_rel_type_code</code>.
     */
    public String getMeaningRelTypeCode() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, Long, String, String, Integer, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, Long, String, String, Integer, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TypeMeaningRelation.MEANING_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return TypeMeaningRelation.LEXEME_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return TypeMeaningRelation.WORD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TypeMeaningRelation.WORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TypeMeaningRelation.WORD_LANG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TypeMeaningRelation.HOMONYM_NR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TypeMeaningRelation.COMPLEXITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TypeMeaningRelation.MEANING_REL_TYPE_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getMeaningId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getLexemeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getWordId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getWord();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getWordLang();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getHomonymNr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getComplexity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getMeaningRelTypeCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getMeaningId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getLexemeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getWordId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getWord();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getWordLang();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getHomonymNr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getComplexity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getMeaningRelTypeCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeMeaningRelationRecord value1(Long value) {
        setMeaningId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeMeaningRelationRecord value2(Long value) {
        setLexemeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeMeaningRelationRecord value3(Long value) {
        setWordId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeMeaningRelationRecord value4(String value) {
        setWord(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeMeaningRelationRecord value5(String value) {
        setWordLang(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeMeaningRelationRecord value6(Integer value) {
        setHomonymNr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeMeaningRelationRecord value7(String value) {
        setComplexity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeMeaningRelationRecord value8(String value) {
        setMeaningRelTypeCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeMeaningRelationRecord values(Long value1, Long value2, Long value3, String value4, String value5, Integer value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TypeMeaningRelationRecord
     */
    public TypeMeaningRelationRecord() {
        super(TypeMeaningRelation.TYPE_MEANING_RELATION);
    }

    /**
     * Create a detached, initialised TypeMeaningRelationRecord
     */
    public TypeMeaningRelationRecord(Long meaningId, Long lexemeId, Long wordId, String word, String wordLang, Integer homonymNr, String complexity, String meaningRelTypeCode) {
        super(TypeMeaningRelation.TYPE_MEANING_RELATION);

        set(0, meaningId);
        set(1, lexemeId);
        set(2, wordId);
        set(3, word);
        set(4, wordLang);
        set(5, homonymNr);
        set(6, complexity);
        set(7, meaningRelTypeCode);
    }
}
