/*
 * This file is generated by jOOQ.
 */
package eki.ekilex.data.db.tables.records;


import eki.ekilex.data.db.tables.FormRelation;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FormRelationRecord extends UpdatableRecordImpl<FormRelationRecord> implements Record5<Long, Long, Long, String, Long> {

    private static final long serialVersionUID = 1024844641;

    /**
     * Setter for <code>public.form_relation.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.form_relation.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.form_relation.form1_id</code>.
     */
    public void setForm1Id(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.form_relation.form1_id</code>.
     */
    public Long getForm1Id() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.form_relation.form2_id</code>.
     */
    public void setForm2Id(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.form_relation.form2_id</code>.
     */
    public Long getForm2Id() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.form_relation.form_rel_type_code</code>.
     */
    public void setFormRelTypeCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.form_relation.form_rel_type_code</code>.
     */
    public String getFormRelTypeCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.form_relation.order_by</code>.
     */
    public void setOrderBy(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.form_relation.order_by</code>.
     */
    public Long getOrderBy() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Long, Long, String, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Long, Long, String, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return FormRelation.FORM_RELATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return FormRelation.FORM_RELATION.FORM1_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return FormRelation.FORM_RELATION.FORM2_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return FormRelation.FORM_RELATION.FORM_REL_TYPE_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return FormRelation.FORM_RELATION.ORDER_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getForm1Id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getForm2Id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getFormRelTypeCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getOrderBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getForm1Id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getForm2Id();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFormRelTypeCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getOrderBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FormRelationRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FormRelationRecord value2(Long value) {
        setForm1Id(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FormRelationRecord value3(Long value) {
        setForm2Id(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FormRelationRecord value4(String value) {
        setFormRelTypeCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FormRelationRecord value5(Long value) {
        setOrderBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FormRelationRecord values(Long value1, Long value2, Long value3, String value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FormRelationRecord
     */
    public FormRelationRecord() {
        super(FormRelation.FORM_RELATION);
    }

    /**
     * Create a detached, initialised FormRelationRecord
     */
    public FormRelationRecord(Long id, Long form1Id, Long form2Id, String formRelTypeCode, Long orderBy) {
        super(FormRelation.FORM_RELATION);

        set(0, id);
        set(1, form1Id);
        set(2, form2Id);
        set(3, formRelTypeCode);
        set(4, orderBy);
    }
}
