/*
 * This file is generated by jOOQ.
 */
package eki.ekilex.data.db.tables.records;


import eki.ekilex.data.db.tables.MorphFreq;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MorphFreqRecord extends UpdatableRecordImpl<MorphFreqRecord> implements Record5<Long, Long, String, BigDecimal, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.morph_freq.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.morph_freq.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.morph_freq.freq_corp_id</code>.
     */
    public void setFreqCorpId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.morph_freq.freq_corp_id</code>.
     */
    public Long getFreqCorpId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.morph_freq.morph_code</code>.
     */
    public void setMorphCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.morph_freq.morph_code</code>.
     */
    public String getMorphCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.morph_freq.value</code>.
     */
    public void setValue(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.morph_freq.value</code>.
     */
    public BigDecimal getValue() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.morph_freq.rank</code>.
     */
    public void setRank(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.morph_freq.rank</code>.
     */
    public Long getRank() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, String, BigDecimal, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, String, BigDecimal, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MorphFreq.MORPH_FREQ.ID;
    }

    @Override
    public Field<Long> field2() {
        return MorphFreq.MORPH_FREQ.FREQ_CORP_ID;
    }

    @Override
    public Field<String> field3() {
        return MorphFreq.MORPH_FREQ.MORPH_CODE;
    }

    @Override
    public Field<BigDecimal> field4() {
        return MorphFreq.MORPH_FREQ.VALUE;
    }

    @Override
    public Field<Long> field5() {
        return MorphFreq.MORPH_FREQ.RANK;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getFreqCorpId();
    }

    @Override
    public String component3() {
        return getMorphCode();
    }

    @Override
    public BigDecimal component4() {
        return getValue();
    }

    @Override
    public Long component5() {
        return getRank();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getFreqCorpId();
    }

    @Override
    public String value3() {
        return getMorphCode();
    }

    @Override
    public BigDecimal value4() {
        return getValue();
    }

    @Override
    public Long value5() {
        return getRank();
    }

    @Override
    public MorphFreqRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MorphFreqRecord value2(Long value) {
        setFreqCorpId(value);
        return this;
    }

    @Override
    public MorphFreqRecord value3(String value) {
        setMorphCode(value);
        return this;
    }

    @Override
    public MorphFreqRecord value4(BigDecimal value) {
        setValue(value);
        return this;
    }

    @Override
    public MorphFreqRecord value5(Long value) {
        setRank(value);
        return this;
    }

    @Override
    public MorphFreqRecord values(Long value1, Long value2, String value3, BigDecimal value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MorphFreqRecord
     */
    public MorphFreqRecord() {
        super(MorphFreq.MORPH_FREQ);
    }

    /**
     * Create a detached, initialised MorphFreqRecord
     */
    public MorphFreqRecord(Long id, Long freqCorpId, String morphCode, BigDecimal value, Long rank) {
        super(MorphFreq.MORPH_FREQ);

        setId(id);
        setFreqCorpId(freqCorpId);
        setMorphCode(morphCode);
        setValue(value);
        setRank(rank);
    }
}
