/*
 * This file is generated by jOOQ.
 */
package eki.ekilex.data.db.tables.records;


import eki.ekilex.data.db.tables.ViewWwLexeme;
import eki.ekilex.data.db.udt.records.TypeGovernmentRecord;
import eki.ekilex.data.db.udt.records.TypeGrammarRecord;
import eki.ekilex.data.db.udt.records.TypeLangComplexityRecord;
import eki.ekilex.data.db.udt.records.TypeMeaningWordRecord;
import eki.ekilex.data.db.udt.records.TypePublicNoteRecord;
import eki.ekilex.data.db.udt.records.TypeUsageRecord;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record21;
import org.jooq.Row21;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewWwLexemeRecord extends TableRecordImpl<ViewWwLexemeRecord> implements Record21<Long, Long, Long, String, String, Integer, Integer, BigDecimal, String, Long, String[], String[], String[], TypeMeaningWordRecord[], String[], TypePublicNoteRecord[], TypeGrammarRecord[], TypeGovernmentRecord[], TypeUsageRecord[], TypeLangComplexityRecord[], String[]> {

    private static final long serialVersionUID = -478737772;

    /**
     * Setter for <code>public.view_ww_lexeme.lexeme_id</code>.
     */
    public void setLexemeId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.view_ww_lexeme.lexeme_id</code>.
     */
    public Long getLexemeId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.view_ww_lexeme.word_id</code>.
     */
    public void setWordId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.view_ww_lexeme.word_id</code>.
     */
    public Long getWordId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.view_ww_lexeme.meaning_id</code>.
     */
    public void setMeaningId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.view_ww_lexeme.meaning_id</code>.
     */
    public Long getMeaningId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.view_ww_lexeme.dataset_type</code>.
     */
    public void setDatasetType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.view_ww_lexeme.dataset_type</code>.
     */
    public String getDatasetType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.view_ww_lexeme.dataset_code</code>.
     */
    public void setDatasetCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.view_ww_lexeme.dataset_code</code>.
     */
    public String getDatasetCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.view_ww_lexeme.level1</code>.
     */
    public void setLevel1(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.view_ww_lexeme.level1</code>.
     */
    public Integer getLevel1() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.view_ww_lexeme.level2</code>.
     */
    public void setLevel2(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.view_ww_lexeme.level2</code>.
     */
    public Integer getLevel2() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.view_ww_lexeme.weight</code>.
     */
    public void setWeight(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.view_ww_lexeme.weight</code>.
     */
    public BigDecimal getWeight() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>public.view_ww_lexeme.complexity</code>.
     */
    public void setComplexity(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.view_ww_lexeme.complexity</code>.
     */
    public String getComplexity() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.view_ww_lexeme.lex_order_by</code>.
     */
    public void setLexOrderBy(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.view_ww_lexeme.lex_order_by</code>.
     */
    public Long getLexOrderBy() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>public.view_ww_lexeme.register_codes</code>.
     */
    public void setRegisterCodes(String... value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.view_ww_lexeme.register_codes</code>.
     */
    public String[] getRegisterCodes() {
        return (String[]) get(10);
    }

    /**
     * Setter for <code>public.view_ww_lexeme.pos_codes</code>.
     */
    public void setPosCodes(String... value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.view_ww_lexeme.pos_codes</code>.
     */
    public String[] getPosCodes() {
        return (String[]) get(11);
    }

    /**
     * Setter for <code>public.view_ww_lexeme.deriv_codes</code>.
     */
    public void setDerivCodes(String... value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.view_ww_lexeme.deriv_codes</code>.
     */
    public String[] getDerivCodes() {
        return (String[]) get(12);
    }

    /**
     * Setter for <code>public.view_ww_lexeme.meaning_words</code>.
     */
    public void setMeaningWords(TypeMeaningWordRecord... value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.view_ww_lexeme.meaning_words</code>.
     */
    public TypeMeaningWordRecord[] getMeaningWords() {
        return (TypeMeaningWordRecord[]) get(13);
    }

    /**
     * Setter for <code>public.view_ww_lexeme.advice_notes</code>.
     */
    public void setAdviceNotes(String... value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.view_ww_lexeme.advice_notes</code>.
     */
    public String[] getAdviceNotes() {
        return (String[]) get(14);
    }

    /**
     * Setter for <code>public.view_ww_lexeme.public_notes</code>.
     */
    public void setPublicNotes(TypePublicNoteRecord... value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.view_ww_lexeme.public_notes</code>.
     */
    public TypePublicNoteRecord[] getPublicNotes() {
        return (TypePublicNoteRecord[]) get(15);
    }

    /**
     * Setter for <code>public.view_ww_lexeme.grammars</code>.
     */
    public void setGrammars(TypeGrammarRecord... value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.view_ww_lexeme.grammars</code>.
     */
    public TypeGrammarRecord[] getGrammars() {
        return (TypeGrammarRecord[]) get(16);
    }

    /**
     * Setter for <code>public.view_ww_lexeme.governments</code>.
     */
    public void setGovernments(TypeGovernmentRecord... value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.view_ww_lexeme.governments</code>.
     */
    public TypeGovernmentRecord[] getGovernments() {
        return (TypeGovernmentRecord[]) get(17);
    }

    /**
     * Setter for <code>public.view_ww_lexeme.usages</code>.
     */
    public void setUsages(TypeUsageRecord... value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.view_ww_lexeme.usages</code>.
     */
    public TypeUsageRecord[] getUsages() {
        return (TypeUsageRecord[]) get(18);
    }

    /**
     * Setter for <code>public.view_ww_lexeme.lang_complexities</code>.
     */
    public void setLangComplexities(TypeLangComplexityRecord... value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.view_ww_lexeme.lang_complexities</code>.
     */
    public TypeLangComplexityRecord[] getLangComplexities() {
        return (TypeLangComplexityRecord[]) get(19);
    }

    /**
     * Setter for <code>public.view_ww_lexeme.od_lexeme_recommendations</code>.
     */
    public void setOdLexemeRecommendations(String... value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.view_ww_lexeme.od_lexeme_recommendations</code>.
     */
    public String[] getOdLexemeRecommendations() {
        return (String[]) get(20);
    }

    // -------------------------------------------------------------------------
    // Record21 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row21<Long, Long, Long, String, String, Integer, Integer, BigDecimal, String, Long, String[], String[], String[], TypeMeaningWordRecord[], String[], TypePublicNoteRecord[], TypeGrammarRecord[], TypeGovernmentRecord[], TypeUsageRecord[], TypeLangComplexityRecord[], String[]> fieldsRow() {
        return (Row21) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row21<Long, Long, Long, String, String, Integer, Integer, BigDecimal, String, Long, String[], String[], String[], TypeMeaningWordRecord[], String[], TypePublicNoteRecord[], TypeGrammarRecord[], TypeGovernmentRecord[], TypeUsageRecord[], TypeLangComplexityRecord[], String[]> valuesRow() {
        return (Row21) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ViewWwLexeme.VIEW_WW_LEXEME.LEXEME_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return ViewWwLexeme.VIEW_WW_LEXEME.WORD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return ViewWwLexeme.VIEW_WW_LEXEME.MEANING_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ViewWwLexeme.VIEW_WW_LEXEME.DATASET_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ViewWwLexeme.VIEW_WW_LEXEME.DATASET_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return ViewWwLexeme.VIEW_WW_LEXEME.LEVEL1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return ViewWwLexeme.VIEW_WW_LEXEME.LEVEL2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field8() {
        return ViewWwLexeme.VIEW_WW_LEXEME.WEIGHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return ViewWwLexeme.VIEW_WW_LEXEME.COMPLEXITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return ViewWwLexeme.VIEW_WW_LEXEME.LEX_ORDER_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field11() {
        return ViewWwLexeme.VIEW_WW_LEXEME.REGISTER_CODES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field12() {
        return ViewWwLexeme.VIEW_WW_LEXEME.POS_CODES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field13() {
        return ViewWwLexeme.VIEW_WW_LEXEME.DERIV_CODES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<TypeMeaningWordRecord[]> field14() {
        return ViewWwLexeme.VIEW_WW_LEXEME.MEANING_WORDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field15() {
        return ViewWwLexeme.VIEW_WW_LEXEME.ADVICE_NOTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<TypePublicNoteRecord[]> field16() {
        return ViewWwLexeme.VIEW_WW_LEXEME.PUBLIC_NOTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<TypeGrammarRecord[]> field17() {
        return ViewWwLexeme.VIEW_WW_LEXEME.GRAMMARS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<TypeGovernmentRecord[]> field18() {
        return ViewWwLexeme.VIEW_WW_LEXEME.GOVERNMENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<TypeUsageRecord[]> field19() {
        return ViewWwLexeme.VIEW_WW_LEXEME.USAGES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<TypeLangComplexityRecord[]> field20() {
        return ViewWwLexeme.VIEW_WW_LEXEME.LANG_COMPLEXITIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field21() {
        return ViewWwLexeme.VIEW_WW_LEXEME.OD_LEXEME_RECOMMENDATIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getLexemeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getWordId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getMeaningId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDatasetType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDatasetCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getLevel1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getLevel2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component8() {
        return getWeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getComplexity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getLexOrderBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] component11() {
        return getRegisterCodes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] component12() {
        return getPosCodes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] component13() {
        return getDerivCodes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeMeaningWordRecord[] component14() {
        return getMeaningWords();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] component15() {
        return getAdviceNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypePublicNoteRecord[] component16() {
        return getPublicNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeGrammarRecord[] component17() {
        return getGrammars();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeGovernmentRecord[] component18() {
        return getGovernments();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeUsageRecord[] component19() {
        return getUsages();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeLangComplexityRecord[] component20() {
        return getLangComplexities();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] component21() {
        return getOdLexemeRecommendations();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getLexemeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getWordId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getMeaningId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDatasetType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDatasetCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getLevel1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getLevel2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value8() {
        return getWeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getComplexity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getLexOrderBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value11() {
        return getRegisterCodes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value12() {
        return getPosCodes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value13() {
        return getDerivCodes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeMeaningWordRecord[] value14() {
        return getMeaningWords();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value15() {
        return getAdviceNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypePublicNoteRecord[] value16() {
        return getPublicNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeGrammarRecord[] value17() {
        return getGrammars();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeGovernmentRecord[] value18() {
        return getGovernments();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeUsageRecord[] value19() {
        return getUsages();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeLangComplexityRecord[] value20() {
        return getLangComplexities();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value21() {
        return getOdLexemeRecommendations();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewWwLexemeRecord value1(Long value) {
        setLexemeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewWwLexemeRecord value2(Long value) {
        setWordId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewWwLexemeRecord value3(Long value) {
        setMeaningId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewWwLexemeRecord value4(String value) {
        setDatasetType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewWwLexemeRecord value5(String value) {
        setDatasetCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewWwLexemeRecord value6(Integer value) {
        setLevel1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewWwLexemeRecord value7(Integer value) {
        setLevel2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewWwLexemeRecord value8(BigDecimal value) {
        setWeight(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewWwLexemeRecord value9(String value) {
        setComplexity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewWwLexemeRecord value10(Long value) {
        setLexOrderBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewWwLexemeRecord value11(String... value) {
        setRegisterCodes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewWwLexemeRecord value12(String... value) {
        setPosCodes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewWwLexemeRecord value13(String... value) {
        setDerivCodes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewWwLexemeRecord value14(TypeMeaningWordRecord... value) {
        setMeaningWords(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewWwLexemeRecord value15(String... value) {
        setAdviceNotes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewWwLexemeRecord value16(TypePublicNoteRecord... value) {
        setPublicNotes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewWwLexemeRecord value17(TypeGrammarRecord... value) {
        setGrammars(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewWwLexemeRecord value18(TypeGovernmentRecord... value) {
        setGovernments(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewWwLexemeRecord value19(TypeUsageRecord... value) {
        setUsages(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewWwLexemeRecord value20(TypeLangComplexityRecord... value) {
        setLangComplexities(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewWwLexemeRecord value21(String... value) {
        setOdLexemeRecommendations(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ViewWwLexemeRecord values(Long value1, Long value2, Long value3, String value4, String value5, Integer value6, Integer value7, BigDecimal value8, String value9, Long value10, String[] value11, String[] value12, String[] value13, TypeMeaningWordRecord[] value14, String[] value15, TypePublicNoteRecord[] value16, TypeGrammarRecord[] value17, TypeGovernmentRecord[] value18, TypeUsageRecord[] value19, TypeLangComplexityRecord[] value20, String[] value21) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewWwLexemeRecord
     */
    public ViewWwLexemeRecord() {
        super(ViewWwLexeme.VIEW_WW_LEXEME);
    }

    /**
     * Create a detached, initialised ViewWwLexemeRecord
     */
    public ViewWwLexemeRecord(Long lexemeId, Long wordId, Long meaningId, String datasetType, String datasetCode, Integer level1, Integer level2, BigDecimal weight, String complexity, Long lexOrderBy, String[] registerCodes, String[] posCodes, String[] derivCodes, TypeMeaningWordRecord[] meaningWords, String[] adviceNotes, TypePublicNoteRecord[] publicNotes, TypeGrammarRecord[] grammars, TypeGovernmentRecord[] governments, TypeUsageRecord[] usages, TypeLangComplexityRecord[] langComplexities, String[] odLexemeRecommendations) {
        super(ViewWwLexeme.VIEW_WW_LEXEME);

        set(0, lexemeId);
        set(1, wordId);
        set(2, meaningId);
        set(3, datasetType);
        set(4, datasetCode);
        set(5, level1);
        set(6, level2);
        set(7, weight);
        set(8, complexity);
        set(9, lexOrderBy);
        set(10, registerCodes);
        set(11, posCodes);
        set(12, derivCodes);
        set(13, meaningWords);
        set(14, adviceNotes);
        set(15, publicNotes);
        set(16, grammars);
        set(17, governments);
        set(18, usages);
        set(19, langComplexities);
        set(20, odLexemeRecommendations);
    }
}
