package eki.common.constant;

public enum LifecycleEntity {

	WORD,
	LEXEME,
	MEANING,
	USAGE,
	USAGE_TRANSLATION,
	USAGE_DEFINITION,
	GOVERNMENT,
	GRAMMAR,
	DEFINITION,
	LEXEME_RELATION,
	MEANING_RELATION,
	WORD_RELATION,
	WORD_ETYMOLOGY,
	WORD_RELATION_GROUP_MEMBER,
	LEARNER_COMMENT,
	@Deprecated
	LEXEME_PUBLIC_NOTE,//FIXME should use LifecycleProperty.PUBLIC_NOTE instead
	@Deprecated
	MEANING_PUBLIC_NOTE,//FIXME should use LifecycleProperty.PUBLIC_NOTE instead
	@Deprecated
	DEFINITION_PUBLIC_NOTE,//FIXME should use LifecycleProperty.PUBLIC_NOTE instead
	SOURCE,
	ATTRIBUTE_FREEFORM
}
