/*
 * This file is generated by jOOQ.
 */
package eki.ekilex.data.db.routines;


import eki.ekilex.data.db.Public;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConvEventTypeToOp extends AbstractRoutine<String> {

    private static final long serialVersionUID = -1000830308;

    /**
     * The parameter <code>public.conv_event_type_to_op.RETURN_VALUE</code>.
     */
    public static final Parameter<String> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>public.conv_event_type_to_op.event_type</code>.
     */
    public static final Parameter<String> EVENT_TYPE = Internal.createParameter("event_type", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * Create a new routine call instance
     */
    public ConvEventTypeToOp() {
        super("conv_event_type_to_op", Public.PUBLIC, org.jooq.impl.SQLDataType.VARCHAR);

        setReturnParameter(RETURN_VALUE);
        addInParameter(EVENT_TYPE);
    }

    /**
     * Set the <code>event_type</code> parameter IN value to the routine
     */
    public void setEventType(String value) {
        setValue(EVENT_TYPE, value);
    }

    /**
     * Set the <code>event_type</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setEventType(Field<String> field) {
        setField(EVENT_TYPE, field);
    }
}
